from flask import Blueprint, render_template, jsonify, request, session
import random

words_bp = Blueprint('words', __name__)

# HSK1 Words Database - 500 words
HSK1_WORDS = [
    
  
  { "id": 1, "word": "爱好", "pinyin": "àihào", "english": "hobby", "options": ["interest", "habit", "favourite", "hobby"], "correctAnswer": 3 },
  { "id": 2, "word": "八", "pinyin": "bā", "english": "eight", "options": ["seven", "eight", "nine", "ten"], "correctAnswer": 1 },
  { "id": 3, "word": "爸爸", "pinyin": "bàba", "english": "dad", "options": ["dad", "uncle", "father", "brother"], "correctAnswer": 0 },
  { "id": 4, "word": "吧", "pinyin": "ba", "english": "sentence-final particle", "options": ["word ending", "suffix", "sentence-final particle", "particle"], "correctAnswer": 2 },
  { "id": 5, "word": "白天", "pinyin": "báitiān", "english": "day", "options": ["night", "noon", "day", "morning"], "correctAnswer": 2 },
  { "id": 6, "word": "百", "pinyin": "bǎi", "english": "hundred", "options": ["hundred", "ten", "million", "thousand"], "correctAnswer": 0 },
  { "id": 7, "word": "班", "pinyin": "bān", "english": "class", "options": ["lesson", "group", "grade", "class"], "correctAnswer": 3 },
  { "id": 8, "word": "半", "pinyin": "bàn", "english": "half", "options": ["half", "some", "middle", "part"], "correctAnswer": 0 },
  { "id": 9, "word": "半年", "pinyin": "bànnián", "english": "half a year", "options": ["few months", "one year", "half a year", "six months"], "correctAnswer": 2 },
  { "id": 10, "word": "半天", "pinyin": "bàntiān", "english": "long time", "options": ["half day", "afternoon", "morning", "long time"], "correctAnswer": 3 },
  { "id": 11, "word": "帮", "pinyin": "bāng", "english": "help", "options": ["support", "save", "help", "assist"], "correctAnswer": 2 },
  { "id": 12, "word": "帮忙", "pinyin": "bāngmáng", "english": "to help", "options": ["to assist", "to work", "to guide", "to help"], "correctAnswer": 3 },
  { "id": 13, "word": "包", "pinyin": "bāo", "english": "package", "options": ["box", "parcel", "package", "bag"], "correctAnswer": 2 },
  { "id": 14, "word": "包子", "pinyin": "bāozi", "english": "bun", "options": ["bun", "cake", "bread", "dumpling"], "correctAnswer": 0 },
  { "id": 15, "word": "杯", "pinyin": "bēi", "english": "cup", "options": ["bottle", "cup", "mug", "glass"], "correctAnswer": 1 },
  { "id": 16, "word": "杯子", "pinyin": "bēizi", "english": "cup", "options": ["plate", "glass", "bottle", "cup"], "correctAnswer": 3 },
  { "id": 17, "word": "北", "pinyin": "běi", "english": "north", "options": ["south", "west", "east", "north"], "correctAnswer": 3 },
  { "id": 18, "word": "北边", "pinyin": "běibian", "english": "north side", "options": ["north area", "north side", "upside", "northern part"], "correctAnswer": 1 },
  { "id": 19, "word": "北京", "pinyin": "Běijīng", "english": "Beijing", "options": ["Shanghai", "Nanjing", "Beijing", "Tianjin"], "correctAnswer": 2 },
  { "id": 20, "word": "本", "pinyin": "běn", "english": "measure word (for books)", "options": ["measure word (for books)", "copy", "volume", "book"], "correctAnswer": 0 },
  { "id": 21, "word": "本子", "pinyin": "běnzi", "english": "notebook", "options": ["file", "diary", "notebook", "book"], "correctAnswer": 2 },
  { "id": 22, "word": "比", "pinyin": "bǐ", "english": "than", "options": ["as", "compare", "by", "than"], "correctAnswer": 3 },
  { "id": 23, "word": "别", "pinyin": "bié", "english": "don’t", "options": ["never", "don’t", "stop", "not"], "correctAnswer": 1 },
  { "id": 24, "word": "别的", "pinyin": "bié de", "english": "other", "options": ["new", "another", "different", "other"], "correctAnswer": 3 },
  { "id": 25, "word": "别人", "pinyin": "biérén", "english": "other people", "options": ["other people", "friends", "others", "people"], "correctAnswer": 0 },
  { "id": 26, "word": "病", "pinyin": "bìng", "english": "disease", "options": ["illness", "disease", "pain", "sickness"], "correctAnswer": 1 },
  { "id": 27, "word": "病人", "pinyin": "bìngrén", "english": "patient", "options": ["doctor", "patient", "sick person", "ill person"], "correctAnswer": 1 },
  { "id": 28, "word": "不大", "pinyin": "bù dà", "english": "not big", "options": ["not big", "tiny", "small", "a little big"], "correctAnswer": 0 },
  { "id": 29, "word": "不对", "pinyin": "bùduì", "english": "wrong", "options": ["incorrect", "false", "not correct", "wrong"], "correctAnswer": 3 },
  { "id": 30, "word": "不客气", "pinyin": "bù kèqì", "english": "you're welcome", "options": ["thank you", "welcome", "no problem", "you're welcome"], "correctAnswer": 3 },
  { "id": 31, "word": "不用", "pinyin": "bùyòng", "english": "no need to", "options": ["no need to", "not needed", "unnecessary", "don’t have to"], "correctAnswer": 0 },
  { "id": 32, "word": "不", "pinyin": "bù", "english": "do not", "options": ["not", "no", "don’t", "do not"], "correctAnswer": 3 },
  { "id": 33, "word": "菜", "pinyin": "cài", "english": "dish", "options": ["dish", "food", "meal", "vegetable"], "correctAnswer": 0 },
  { "id": 34, "word": "茶", "pinyin": "chá", "english": "tea", "options": ["milk", "coffee", "juice", "tea"], "correctAnswer": 3 },
  { "id": 35, "word": "差", "pinyin": "chà", "english": "difference", "options": ["different", "bad", "difference", "less"], "correctAnswer": 2 },
  { "id": 36, "word": "常", "pinyin": "cháng", "english": "often", "options": ["always", "usually", "sometimes", "often"], "correctAnswer": 3 },
  { "id": 37, "word": "常常", "pinyin": "chángcháng", "english": "often", "options": ["frequently", "regularly", "usually", "often"], "correctAnswer": 3 },
  { "id": 38, "word": "唱", "pinyin": "chàng", "english": "to sing", "options": ["to dance", "to sing", "to shout", "to play"], "correctAnswer": 1 },
  { "id": 39, "word": "唱歌", "pinyin": "chànggē", "english": "to sing", "options": ["to sing", "to play music", "to sing songs", "to dance"], "correctAnswer": 0 },
  { "id": 40, "word": "车", "pinyin": "chē", "english": "car", "options": ["train", "bike", "car", "bus"], "correctAnswer": 2 },
  { "id": 41, "word": "车票", "pinyin": "chēpiào", "english": "ticket", "options": ["ticket", "bus ticket", "train ticket", "pass"], "correctAnswer": 0 },
  { "id": 42, "word": "车上", "pinyin": "chē shàng", "english": "in the car", "options": ["inside", "in vehicle", "on the bus", "in the car"], "correctAnswer": 3 },
  { "id": 43, "word": "车站", "pinyin": "chēzhàn", "english": "station", "options": ["station", "stop", "parking", "terminal"], "correctAnswer": 0 },
  { "id": 44, "word": "吃", "pinyin": "chī", "english": "eat", "options": ["taste", "eat", "chew", "drink"], "correctAnswer": 1 },
  { "id": 45, "word": "吃饭", "pinyin": "chīfàn", "english": "eat (a meal)", "options": ["to eat", "eat (a meal)", "have lunch", "to dine"], "correctAnswer": 1 },
  { "id": 46, "word": "出", "pinyin": "chū", "english": "out", "options": ["go out", "out", "leave", "exit"], "correctAnswer": 1 },
  { "id": 47, "word": "出来", "pinyin": "chūlái", "english": "come out", "options": ["come out", "walk out", "leave", "go out"], "correctAnswer": 0 },
  { "id": 48, "word": "出去", "pinyin": "chūqù", "english": "go out", "options": ["leave", "come out", "go out", "go away"], "correctAnswer": 2 },
  { "id": 49, "word": "穿", "pinyin": "chuān", "english": "wear", "options": ["dress", "wear", "use", "put on"], "correctAnswer": 1 },
  { "id": 50, "word": "床", "pinyin": "chuáng", "english": "bed", "options": ["bed", "chair", "sofa", "table"], "correctAnswer": 0 },
  
  { "id": 51, "word": "次", "pinyin": "cì", "english": "times (measure word)", "options": ["frequency", "round", "order", "times (measure word)"], "correctAnswer": 3 },
  { "id": 52, "word": "从", "pinyin": "cóng", "english": "from", "options": ["to", "for", "since", "from"], "correctAnswer": 3 },
  { "id": 53, "word": "错", "pinyin": "cuò", "english": "wrong", "options": ["false", "mistake", "wrong", "error"], "correctAnswer": 2 },
  { "id": 54, "word": "打", "pinyin": "dǎ", "english": "to hit", "options": ["to touch", "to beat", "to kick", "to hit"], "correctAnswer": 3 },
  { "id": 55, "word": "打车", "pinyin": "dǎchē", "english": "take a taxi", "options": ["take a bus", "take a train", "take a taxi", "drive a car"], "correctAnswer": 2 },
  { "id": 56, "word": "打电话", "pinyin": "dǎ diànhuà", "english": "make a call", "options": ["answer a call", "send a message", "make a call", "pick up the phone"], "correctAnswer": 2 },
  { "id": 57, "word": "打开", "pinyin": "dǎkāi", "english": "turn on", "options": ["switch off", "open", "turn on", "unlock"], "correctAnswer": 2 },
  { "id": 58, "word": "打球", "pinyin": "dǎqiú", "english": "play ball games", "options": ["play cards", "play ball games", "watch sports", "hit the ball"], "correctAnswer": 1 },
  { "id": 59, "word": "大", "pinyin": "dà", "english": "big", "options": ["small", "huge", "tall", "big"], "correctAnswer": 3 },
  { "id": 60, "word": "大学", "pinyin": "dàxué", "english": "university", "options": ["college", "high school", "academy", "university"], "correctAnswer": 3 },
  { "id": 61, "word": "大学生", "pinyin": "dàxuéshēng", "english": "college student", "options": ["teacher", "student", "college student", "researcher"], "correctAnswer": 2 },
  { "id": 62, "word": "到", "pinyin": "dào", "english": "to; arrive", "options": ["from", "come", "go", "to; arrive"], "correctAnswer": 3 },
  { "id": 63, "word": "得到", "pinyin": "dédào", "english": "to get", "options": ["to earn", "to get", "to reach", "to have"], "correctAnswer": 1 },
  { "id": 64, "word": "地", "pinyin": "de", "english": "structural particle (after adjective)", "options": ["structural particle (after adjective)", "particle (after noun)", "modal particle", "structural particle (after verb)"], "correctAnswer": 0 },
  { "id": 65, "word": "的", "pinyin": "de", "english": "structural particle (after attribute)", "options": ["possessive particle", "structural particle (after attribute)", "modal word", "final particle"], "correctAnswer": 1 },
  { "id": 66, "word": "等", "pinyin": "děng", "english": "to wait", "options": ["to stay", "to rest", "to wait", "to stop"], "correctAnswer": 2 },
  { "id": 67, "word": "地", "pinyin": "dì", "english": "ground", "options": ["earth", "floor", "soil", "ground"], "correctAnswer": 3 },
  { "id": 68, "word": "地点", "pinyin": "dìdiǎn", "english": "location", "options": ["address", "site", "place", "location"], "correctAnswer": 3 },
  { "id": 69, "word": "地方", "pinyin": "dìfāng", "english": "local; location", "options": ["area", "local; location", "site", "town"], "correctAnswer": 1 },
  { "id": 70, "word": "地上", "pinyin": "dìshàng", "english": "on the ground", "options": ["under the ground", "on the floor", "below", "on the ground"], "correctAnswer": 3 },
  { "id": 71, "word": "地图", "pinyin": "dìtú", "english": "map", "options": ["map", "guide", "globe", "plan"], "correctAnswer": 0 },
  { "id": 72, "word": "弟弟", "pinyin": "dìdi", "english": "younger brother", "options": ["older brother", "younger brother", "cousin", "friend"], "correctAnswer": 1 },
  { "id": 73, "word": "第（第二）", "pinyin": "dì (dì èr)", "english": "No. (second)", "options": ["first", "second", "No. (second)", "number"], "correctAnswer": 2 },
  { "id": 74, "word": "点", "pinyin": "diǎn", "english": "o'clock; point", "options": ["hour", "dot", "o'clock; point", "time"], "correctAnswer": 2 },
  { "id": 75, "word": "电", "pinyin": "diàn", "english": "electricity", "options": ["light", "energy", "electricity", "power"], "correctAnswer": 2 },
  { "id": 76, "word": "电话", "pinyin": "diànhuà", "english": "phone", "options": ["call", "telephone", "mobile", "phone"], "correctAnswer": 3 },
  { "id": 77, "word": "电脑", "pinyin": "diànnǎo", "english": "computer", "options": ["laptop", "PC", "computer", "device"], "correctAnswer": 2 },
  { "id": 78, "word": "电视", "pinyin": "diànshì", "english": "TV", "options": ["radio", "screen", "television", "TV"], "correctAnswer": 3 },
  { "id": 79, "word": "电视机", "pinyin": "diànshì jī", "english": "TV set", "options": ["TV set", "television", "monitor", "screen"], "correctAnswer": 0 },
  { "id": 80, "word": "电影", "pinyin": "diànyǐng", "english": "movie", "options": ["show", "movie", "film", "video"], "correctAnswer": 1 },
  { "id": 81, "word": "电影院", "pinyin": "diànyǐngyuàn", "english": "cinema", "options": ["movie hall", "theatre", "cinema", "TV room"], "correctAnswer": 2 },
  { "id": 82, "word": "东", "pinyin": "dōng", "english": "east", "options": ["north", "south", "east", "west"], "correctAnswer": 2 },
  { "id": 83, "word": "东边", "pinyin": "dōngbian", "english": "east side", "options": ["east side", "north side", "south side", "west side"], "correctAnswer": 0 },
  { "id": 84, "word": "东西", "pinyin": "dōngxī", "english": "thing", "options": ["item", "object", "thing", "stuff"], "correctAnswer": 2 },
  { "id": 85, "word": "动", "pinyin": "dòng", "english": "to move", "options": ["to move", "to shake", "to turn", "to lift"], "correctAnswer": 0 },
  { "id": 86, "word": "动作", "pinyin": "dòngzuò", "english": "action", "options": ["gesture", "movement", "action", "activity"], "correctAnswer": 2 },
  { "id": 87, "word": "都", "pinyin": "dōu", "english": "all", "options": ["every", "whole", "both", "all"], "correctAnswer": 3 },
  { "id": 88, "word": "读", "pinyin": "dú", "english": "to read", "options": ["to write", "to study", "to read", "to recite"], "correctAnswer": 2 },
  { "id": 89, "word": "读书", "pinyin": "dúshū", "english": "reading; to study", "options": ["to learn", "reading; to study", "to write", "education"], "correctAnswer": 1 },
  { "id": 90, "word": "对", "pinyin": "duì", "english": "right", "options": ["wrong", "true", "right", "okay"], "correctAnswer": 2 },
  { "id": 91, "word": "对不起", "pinyin": "duìbuqǐ", "english": "I am sorry", "options": ["excuse me", "thank you", "sorry", "I am sorry"], "correctAnswer": 3 },
  { "id": 92, "word": "多", "pinyin": "duō", "english": "many; much", "options": ["plenty", "many; much", "few", "a lot"], "correctAnswer": 1 },
  { "id": 93, "word": "多少", "pinyin": "duōshǎo", "english": "how many; how much", "options": ["how many; how much", "a few", "some", "more or less"], "correctAnswer": 0 },
  { "id": 94, "word": "饿", "pinyin": "è", "english": "hungry", "options": ["hungry", "tired", "thirsty", "sleepy"], "correctAnswer": 0 },
  { "id": 95, "word": "儿子", "pinyin": "érzi", "english": "son", "options": ["boy", "child", "son", "brother"], "correctAnswer": 2 },
  { "id": 96, "word": "二", "pinyin": "èr", "english": "two", "options": ["second", "pair", "two", "double"], "correctAnswer": 2 },
  { "id": 97, "word": "饭", "pinyin": "fàn", "english": "rice; meal", "options": ["food", "rice; meal", "breakfast", "dinner"], "correctAnswer": 1 },
  { "id": 98, "word": "饭店", "pinyin": "fàndiàn", "english": "restaurant", "options": ["canteen", "hotel", "restaurant", "shop"], "correctAnswer": 2 },
  { "id": 99, "word": "房间", "pinyin": "fángjiān", "english": "room", "options": ["hall", "room", "space", "bedroom"], "correctAnswer": 1 },
  { "id": 100, "word": "房子", "pinyin": "fángzi", "english": "house", "options": ["apartment", "building", "house", "home"], "correctAnswer": 2 },
  
  { "id": 101, "word": "放", "pinyin": "fàng", "english": "to put", "options": ["to place", "to keep", "to set", "to put"], "correctAnswer": 3 },
  { "id": 102, "word": "放假", "pinyin": "fàngjià", "english": "holiday; vacation", "options": ["holiday; vacation", "weekend", "break", "rest"], "correctAnswer": 0 },
  { "id": 103, "word": "放学", "pinyin": "fàngxué", "english": "after school", "options": ["school time", "end of class", "after school", "study time"], "correctAnswer": 2 },
  { "id": 104, "word": "飞", "pinyin": "fēi", "english": "to fly", "options": ["to jump", "to move", "to fly", "to run"], "correctAnswer": 2 },
  { "id": 105, "word": "飞机", "pinyin": "fēijī", "english": "airplane", "options": ["plane", "airplane", "helicopter", "jet"], "correctAnswer": 1 },
  { "id": 106, "word": "非常", "pinyin": "fēicháng", "english": "very", "options": ["quite", "too", "very", "so"], "correctAnswer": 2 },
  { "id": 107, "word": "分", "pinyin": "fēn", "english": "minute; point", "options": ["minute; point", "second", "moment", "time"], "correctAnswer": 0 },
  { "id": 108, "word": "风", "pinyin": "fēng", "english": "wind", "options": ["wind", "breeze", "air", "storm"], "correctAnswer": 0 },
  { "id": 109, "word": "干", "pinyin": "gān", "english": "dry", "options": ["wet", "dry", "clean", "empty"], "correctAnswer": 1 },
  { "id": 110, "word": "干净", "pinyin": "gānjìng", "english": "clean", "options": ["tidy", "pure", "clean", "neat"], "correctAnswer": 2 },
  { "id": 111, "word": "干", "pinyin": "gàn", "english": "to do", "options": ["to make", "to act", "to do", "to perform"], "correctAnswer": 2 },
  { "id": 112, "word": "干什么", "pinyin": "gànshénme", "english": "what to do", "options": ["what work", "what to do", "how to do", "what happen"], "correctAnswer": 1 },
  { "id": 113, "word": "高", "pinyin": "gāo", "english": "high; tall", "options": ["big", "tall", "long", "high; tall"], "correctAnswer": 3 },
  { "id": 114, "word": "高兴", "pinyin": "gāoxìng", "english": "happy", "options": ["glad", "joyful", "pleased", "happy"], "correctAnswer": 3 },
  { "id": 115, "word": "告诉", "pinyin": "gàosù", "english": "to tell", "options": ["to say", "to inform", "to speak", "to tell"], "correctAnswer": 3 },
  { "id": 116, "word": "哥哥", "pinyin": "gēge", "english": "elder brother", "options": ["elder brother", "younger brother", "male friend", "sibling"], "correctAnswer": 0 },
  { "id": 117, "word": "歌", "pinyin": "gē", "english": "song", "options": ["poem", "song", "music", "tune"], "correctAnswer": 1 },
  { "id": 118, "word": "个", "pinyin": "gè", "english": "measure word (general)", "options": ["measure word (general)", "classifier for people", "count word", "unit"], "correctAnswer": 0 },
  { "id": 119, "word": "给", "pinyin": "gěi", "english": "to give", "options": ["to bring", "to offer", "to give", "to send"], "correctAnswer": 2 },
  { "id": 120, "word": "跟", "pinyin": "gēn", "english": "with; and", "options": ["and", "with; and", "together", "by"], "correctAnswer": 1 },
  { "id": 121, "word": "工人", "pinyin": "gōngrén", "english": "worker", "options": ["employee", "laborer", "worker", "staff"], "correctAnswer": 2 },
  { "id": 122, "word": "工作", "pinyin": "gōngzuò", "english": "work; job", "options": ["task", "work; job", "profession", "office"], "correctAnswer": 1 },
  { "id": 123, "word": "关", "pinyin": "guān", "english": "to turn off", "options": ["to close", "to stop", "to turn off", "to shut"], "correctAnswer": 2 },
  { "id": 124, "word": "关上", "pinyin": "guānshàng", "english": "to close", "options": ["to shut", "to close", "to block", "to stop"], "correctAnswer": 1 },
  { "id": 125, "word": "贵", "pinyin": "guì", "english": "expensive", "options": ["valuable", "expensive", "costly", "dear"], "correctAnswer": 1 },
  { "id": 126, "word": "国", "pinyin": "guó", "english": "country", "options": ["state", "land", "country", "nation"], "correctAnswer": 2 },
  { "id": 127, "word": "国家", "pinyin": "guójiā", "english": "country; nation", "options": ["homeland", "country; nation", "republic", "kingdom"], "correctAnswer": 1 },
  { "id": 128, "word": "国外", "pinyin": "guówài", "english": "foreign; abroad", "options": ["outside", "foreign; abroad", "overseas", "away"], "correctAnswer": 1 },
  { "id": 129, "word": "过", "pinyin": "guò", "english": "to pass; to cross", "options": ["to cross", "to pass; to cross", "to move", "to go through"], "correctAnswer": 1 },
  { "id": 130, "word": "还", "pinyin": "hái", "english": "still; also", "options": ["also", "again", "still; also", "too"], "correctAnswer": 2 },
  { "id": 131, "word": "还是", "pinyin": "háishì", "english": "or; still is", "options": ["or; still is", "as well", "still", "maybe"], "correctAnswer": 0 },
  { "id": 132, "word": "还有", "pinyin": "háiyǒu", "english": "and also; in addition", "options": ["and also; in addition", "still have", "also", "as well"], "correctAnswer": 0 },
  { "id": 133, "word": "孩子", "pinyin": "háizi", "english": "child", "options": ["boy", "baby", "child", "kid"], "correctAnswer": 2 },
  { "id": 134, "word": "汉语", "pinyin": "Hànyǔ", "english": "Chinese (language)", "options": ["Mandarin", "Chinese (language)", "Cantonese", "language"], "correctAnswer": 1 },
  { "id": 135, "word": "汉字", "pinyin": "Hànzì", "english": "Chinese character", "options": ["word", "Chinese character", "letter", "symbol"], "correctAnswer": 1 },
  { "id": 136, "word": "好", "pinyin": "hǎo", "english": "good", "options": ["fine", "nice", "okay", "good"], "correctAnswer": 3 },
  { "id": 137, "word": "好吃", "pinyin": "hǎochī", "english": "delicious", "options": ["tasty", "delicious", "yummy", "good"], "correctAnswer": 1 },
  { "id": 138, "word": "好看", "pinyin": "hǎokàn", "english": "good looking; pretty", "options": ["beautiful", "pretty", "good looking; pretty", "nice"], "correctAnswer": 2 },
  { "id": 139, "word": "好听", "pinyin": "hǎotīng", "english": "pleasant to hear", "options": ["nice sound", "pleasant to hear", "sweet", "melodious"], "correctAnswer": 1 },
  { "id": 140, "word": "好玩儿", "pinyin": "hǎowánr", "english": "fun", "options": ["fun", "funny", "interesting", "enjoyable"], "correctAnswer": 0 },
  { "id": 141, "word": "号", "pinyin": "hào", "english": "number; date", "options": ["date", "number; date", "day", "count"], "correctAnswer": 1 },
  { "id": 142, "word": "喝", "pinyin": "hē", "english": "to drink", "options": ["to sip", "to swallow", "to drink", "to eat"], "correctAnswer": 2 },
  { "id": 143, "word": "和", "pinyin": "hé", "english": "with; and", "options": ["with; and", "plus", "along", "and also"], "correctAnswer": 0 },
  { "id": 144, "word": "很", "pinyin": "hěn", "english": "very", "options": ["really", "too", "very", "quite"], "correctAnswer": 2 },
  { "id": 145, "word": "后", "pinyin": "hòu", "english": "behind; after", "options": ["later", "behind; after", "back", "next"], "correctAnswer": 1 },
  { "id": 146, "word": "后边", "pinyin": "hòubian", "english": "behind", "options": ["after", "back side", "behind", "rear"], "correctAnswer": 2 },
  { "id": 147, "word": "后天", "pinyin": "hòutiān", "english": "the day after tomorrow", "options": ["tomorrow", "yesterday", "later", "the day after tomorrow"], "correctAnswer": 3 },
  { "id": 148, "word": "花", "pinyin": "huā", "english": "flower", "options": ["flower", "plant", "leaf", "blossom"], "correctAnswer": 0 },
  { "id": 149, "word": "话", "pinyin": "huà", "english": "words; speech", "options": ["language", "speech", "talk", "words; speech"], "correctAnswer": 3 },
  { "id": 150, "word": "坏", "pinyin": "huài", "english": "bad", "options": ["broken", "wrong", "bad", "poor"], "correctAnswer": 2 },
  
  { "id": 151, "word": "还", "pinyin": "huán", "english": "to return (something)", "options": ["to borrow", "to lend", "to exchange", "to return (something)"], "correctAnswer": 3 },
  { "id": 152, "word": "回", "pinyin": "huí", "english": "to go back", "options": ["to stay", "to go back", "to forward", "to move"], "correctAnswer": 2 },
  { "id": 153, "word": "回答", "pinyin": "huídá", "english": "to reply; answer", "options": ["to ask", "to question", "to answer", "to discuss"], "correctAnswer": 0 },
  { "id": 154, "word": "回到", "pinyin": "huí dào", "english": "to return to", "options": ["to arrive", "to reach", "to return to", "to leave"], "correctAnswer": 1 },
  { "id": 155, "word": "回家", "pinyin": "huí jiā", "english": "to go back home", "options": ["to travel", "to move out", "to rest", "to go back home"], "correctAnswer": 3 },
  { "id": 156, "word": "回来", "pinyin": "huílái", "english": "to come back", "options": ["to arrive", "to return", "to come back", "to go"], "correctAnswer": 2 },
  { "id": 157, "word": "回去", "pinyin": "huíqù", "english": "to go back", "options": ["to return", "to come back", "to go", "to go back"], "correctAnswer": 0 },
  { "id": 158, "word": "会", "pinyin": "huì", "english": "can; will", "options": ["must", "can; will", "should", "may"], "correctAnswer": 2 },
  { "id": 159, "word": "火车", "pinyin": "huǒchē", "english": "train", "options": ["car", "bus", "train", "ship"], "correctAnswer": 2 },
  { "id": 160, "word": "机场", "pinyin": "jīchǎng", "english": "airport", "options": ["station", "airport", "port", "bus stop"], "correctAnswer": 1 },
  { "id": 161, "word": "机票", "pinyin": "jīpiào", "english": "air ticket", "options": ["passport", "air ticket", "boarding pass", "visa"], "correctAnswer": 2 },
  { "id": 162, "word": "鸡蛋", "pinyin": "jīdàn", "english": "egg", "options": ["milk", "meat", "egg", "rice"], "correctAnswer": 2 },
  { "id": 163, "word": "几", "pinyin": "jǐ", "english": "a few; how many", "options": ["some", "a few; how many", "none", "many"], "correctAnswer": 1 },
  { "id": 164, "word": "记", "pinyin": "jì", "english": "to remember", "options": ["to remind", "to write", "to remember", "to think"], "correctAnswer": 2 },
  { "id": 165, "word": "记得", "pinyin": "jìde", "english": "to remember", "options": ["to forget", "to remember", "to notice", "to recall"], "correctAnswer": 2 },
  { "id": 166, "word": "记住", "pinyin": "jìzhù", "english": "to remember", "options": ["to forget", "to note", "to remember", "to memorize"], "correctAnswer": 2 },
  { "id": 167, "word": "家", "pinyin": "jiā", "english": "family", "options": ["room", "building", "family", "place"], "correctAnswer": 2 },
  { "id": 168, "word": "家里", "pinyin": "jiālǐ", "english": "at home", "options": ["outside", "in school", "at home", "in class"], "correctAnswer": 2 },
  { "id": 169, "word": "家人", "pinyin": "jiārén", "english": "family member", "options": ["relative", "friend", "neighbor", "family member"], "correctAnswer": 3 },
  { "id": 170, "word": "间", "pinyin": "jiān", "english": "between", "options": ["space", "between", "door", "floor"], "correctAnswer": 1 },
  { "id": 171, "word": "见", "pinyin": "jiàn", "english": "to see", "options": ["to look", "to view", "to meet", "to see"], "correctAnswer": 3 },
  { "id": 172, "word": "见面", "pinyin": "jiànmiàn", "english": "to meet", "options": ["to talk", "to call", "to see", "to meet"], "correctAnswer": 3 },
  { "id": 173, "word": "教", "pinyin": "jiāo", "english": "to teach", "options": ["to learn", "to teach", "to speak", "to read"], "correctAnswer": 1 },
  { "id": 174, "word": "叫", "pinyin": "jiào", "english": "to be called", "options": ["to shout", "to be called", "to say", "to name"], "correctAnswer": 1 },
  { "id": 175, "word": "教学楼", "pinyin": "jiàoxuélóu", "english": "teaching building", "options": ["school gate", "office", "teaching building", "library"], "correctAnswer": 2 },
  { "id": 176, "word": "姐姐", "pinyin": "jiějie", "english": "elder sister", "options": ["aunt", "younger sister", "elder sister", "mother"], "correctAnswer": 2 },
  { "id": 177, "word": "介绍", "pinyin": "jièshào", "english": "introduction", "options": ["to explain", "to meet", "introduction", "to present"], "correctAnswer": 2 },
  { "id": 178, "word": "今年", "pinyin": "jīnnián", "english": "this year", "options": ["last year", "next year", "this year", "that year"], "correctAnswer": 2 },
  { "id": 179, "word": "今天", "pinyin": "jīntiān", "english": "today", "options": ["tomorrow", "yesterday", "today", "now"], "correctAnswer": 2 },
  { "id": 180, "word": "进", "pinyin": "jìn", "english": "to enter", "options": ["to exit", "to go", "to come", "to enter"], "correctAnswer": 3 },
  { "id": 181, "word": "进来", "pinyin": "jìnlái", "english": "to come in", "options": ["to go in", "to come out", "to enter", "to come in"], "correctAnswer": 3 },
  { "id": 182, "word": "进去", "pinyin": "jìnqù", "english": "to go in", "options": ["to leave", "to come out", "to enter", "to go in"], "correctAnswer": 3 },
  { "id": 183, "word": "九", "pinyin": "jiǔ", "english": "nine", "options": ["eight", "nine", "ten", "seven"], "correctAnswer": 1 },
  { "id": 184, "word": "就", "pinyin": "jiù", "english": "on", "options": ["but", "on", "because", "so"], "correctAnswer": 1 },
  { "id": 185, "word": "觉得", "pinyin": "juéde", "english": "to feel", "options": ["to think", "to believe", "to decide", "to feel"], "correctAnswer": 3 },
  { "id": 186, "word": "开", "pinyin": "kāi", "english": "to open", "options": ["to open", "to close", "to break", "to turn"], "correctAnswer": 0 },
  { "id": 187, "word": "开车", "pinyin": "kāichē", "english": "to drive", "options": ["to ride", "to drive", "to fly", "to travel"], "correctAnswer": 1 },
  { "id": 188, "word": "开会", "pinyin": "kāihuì", "english": "to have a meeting", "options": ["to organize", "to attend class", "to have a meeting", "to work"], "correctAnswer": 2 },
  { "id": 189, "word": "开玩笑", "pinyin": "kāi wánxiào", "english": "to joke", "options": ["to laugh", "to joke", "to play", "to chat"], "correctAnswer": 1 },
  { "id": 190, "word": "看", "pinyin": "kàn", "english": "to look", "options": ["to view", "to read", "to see", "to look"], "correctAnswer": 3 },
  { "id": 191, "word": "看病", "pinyin": "kànbìng", "english": "to see a doctor", "options": ["to check", "to see a doctor", "to visit", "to rest"], "correctAnswer": 1 },
  { "id": 192, "word": "看到", "pinyin": "kàn dào", "english": "to see", "options": ["to watch", "to hear", "to see", "to look"], "correctAnswer": 2 },
  { "id": 193, "word": "看见", "pinyin": "kànjiàn", "english": "to see", "options": ["to observe", "to notice", "to see", "to find"], "correctAnswer": 2 },
  { "id": 194, "word": "考", "pinyin": "kǎo", "english": "to test", "options": ["to check", "to examine", "to test", "to try"], "correctAnswer": 2 },
  { "id": 195, "word": "考试", "pinyin": "kǎoshì", "english": "exam", "options": ["to test", "exam", "assignment", "class"], "correctAnswer": 1 },
  { "id": 196, "word": "渴", "pinyin": "kě", "english": "thirsty", "options": ["hungry", "tired", "thirsty", "sleepy"], "correctAnswer": 2 },
  { "id": 197, "word": "课", "pinyin": "kè", "english": "class", "options": ["subject", "class", "lecture", "topic"], "correctAnswer": 1 },
  { "id": 198, "word": "课本", "pinyin": "kèběn", "english": "textbook", "options": ["book", "textbook", "magazine", "notebook"], "correctAnswer": 1 },
  { "id": 199, "word": "课文", "pinyin": "kèwén", "english": "text", "options": ["context", "lesson", "paragraph", "text"], "correctAnswer": 3 },
  { "id": 200, "word": "口", "pinyin": "kǒu", "english": "mouth", "options": ["face", "mouth", "head", "eye"], "correctAnswer": 1 },
  
  { "id": 201, "word": "块", "pinyin": "kuài", "english": "piece; yuan", "options": ["money", "block", "piece; yuan", "part"], "correctAnswer": 2 },
  { "id": 202, "word": "快", "pinyin": "kuài", "english": "fast; quick", "options": ["slow", "early", "fast; quick", "soon"], "correctAnswer": 2 },
  { "id": 203, "word": "来", "pinyin": "lái", "english": "to come", "options": ["to go", "to enter", "to come", "to return"], "correctAnswer": 2 },
  { "id": 204, "word": "来到", "pinyin": "lái dào", "english": "to come to", "options": ["to leave", "to approach", "to come to", "to go back"], "correctAnswer": 2 },
  { "id": 205, "word": "老", "pinyin": "lǎo", "english": "old", "options": ["young", "fresh", "old", "ancient"], "correctAnswer": 2 },
  { "id": 206, "word": "老人", "pinyin": "lǎorén", "english": "old person; the elderly", "options": ["old man", "aged", "old person; the elderly", "grandparent"], "correctAnswer": 2 },
  { "id": 207, "word": "老师", "pinyin": "lǎoshī", "english": "teacher", "options": ["student", "teacher", "doctor", "worker"], "correctAnswer": 1 },
  { "id": 208, "word": "了", "pinyin": "le", "english": "particle (completed action)", "options": ["past", "future", "particle (completed action)", "none"], "correctAnswer": 2 },
  { "id": 209, "word": "累", "pinyin": "lèi", "english": "tired", "options": ["sleepy", "lazy", "tired", "hungry"], "correctAnswer": 2 },
  { "id": 210, "word": "冷", "pinyin": "lěng", "english": "cold", "options": ["hot", "cool", "cold", "warm"], "correctAnswer": 2 },
  { "id": 211, "word": "里", "pinyin": "lǐ", "english": "in; inside", "options": ["outside", "within", "in; inside", "below"], "correctAnswer": 2 },
  { "id": 212, "word": "里边", "pinyin": "lǐbian", "english": "inside", "options": ["outside", "under", "inside", "behind"], "correctAnswer": 2 },
  { "id": 213, "word": "两", "pinyin": "liǎng", "english": "two (countable)", "options": ["double", "pair", "two (countable)", "both"], "correctAnswer": 2 },
  { "id": 214, "word": "零", "pinyin": "líng", "english": "zero", "options": ["none", "zero", "empty", "null"], "correctAnswer": 1 },
  { "id": 215, "word": "六", "pinyin": "liù", "english": "six", "options": ["six", "seven", "five", "nine"], "correctAnswer": 0 },
  { "id": 216, "word": "楼", "pinyin": "lóu", "english": "building; floor", "options": ["room", "building; floor", "house", "apartment"], "correctAnswer": 1 },
  { "id": 217, "word": "楼上", "pinyin": "lóu shàng", "english": "upstairs", "options": ["downstairs", "upstairs", "rooftop", "basement"], "correctAnswer": 1 },
  { "id": 218, "word": "楼下", "pinyin": "lóu xià", "english": "downstairs", "options": ["upstairs", "downstairs", "outside", "below"], "correctAnswer": 1 },
  { "id": 219, "word": "路", "pinyin": "lù", "english": "road", "options": ["street", "road", "pathway", "bridge"], "correctAnswer": 1 },
  { "id": 220, "word": "路口", "pinyin": "lùkǒu", "english": "intersection", "options": ["crossroad", "corner", "junction", "intersection"], "correctAnswer": 3 },
  { "id": 221, "word": "路上", "pinyin": "lùshàng", "english": "on the road", "options": ["at home", "on the road", "at work", "in the city"], "correctAnswer": 1 },
  { "id": 222, "word": "妈妈", "pinyin": "māma", "english": "mom", "options": ["mom", "sister", "aunt", "mother"], "correctAnswer": 0 },
  { "id": 223, "word": "马路", "pinyin": "mǎlù", "english": "road; street", "options": ["road; street", "bridge", "way", "lane"], "correctAnswer": 0 },
  { "id": 224, "word": "马上", "pinyin": "mǎshàng", "english": "immediately", "options": ["quickly", "soon", "instantly", "immediately"], "correctAnswer": 3 },
  { "id": 225, "word": "吗", "pinyin": "ma", "english": "question particle", "options": ["modal word", "question particle", "end word", "tone marker"], "correctAnswer": 1 },
  { "id": 226, "word": "买", "pinyin": "mǎi", "english": "to buy", "options": ["to buy", "to sell", "to take", "to borrow"], "correctAnswer": 0 },
  { "id": 227, "word": "慢", "pinyin": "màn", "english": "slow", "options": ["fast", "lazy", "slow", "steady"], "correctAnswer": 2 },
  { "id": 228, "word": "忙", "pinyin": "máng", "english": "busy", "options": ["tired", "busy", "active", "working"], "correctAnswer": 1 },
  { "id": 229, "word": "毛", "pinyin": "máo", "english": "measure word (10 cents)", "options": ["coin", "measure word (10 cents)", "money", "cent"], "correctAnswer": 1 },
  { "id": 230, "word": "没", "pinyin": "méi", "english": "not (have); no", "options": ["nothing", "not (have); no", "none", "missing"], "correctAnswer": 1 },
  { "id": 231, "word": "没关系", "pinyin": "méi guānxi", "english": "it's okay; no problem", "options": ["never mind", "no worries", "it’s fine", "it's okay; no problem"], "correctAnswer": 3 },
  { "id": 232, "word": "没什么", "pinyin": "méi shénme", "english": "it's nothing", "options": ["no big deal", "it's nothing", "it’s fine", "never mind"], "correctAnswer": 1 },
  { "id": 233, "word": "没事儿", "pinyin": "méi shìr", "english": "it's okay; no problem", "options": ["no trouble", "it's okay; no problem", "don’t worry", "fine"], "correctAnswer": 1 },
  { "id": 234, "word": "没有", "pinyin": "méiyǒu", "english": "to not have; there is not", "options": ["have", "to not have; there is not", "own", "keep"], "correctAnswer": 1 },
  { "id": 235, "word": "妹妹", "pinyin": "mèimei", "english": "younger sister", "options": ["elder sister", "younger sister", "aunt", "cousin"], "correctAnswer": 1 },
  { "id": 236, "word": "门", "pinyin": "mén", "english": "door", "options": ["window", "door", "gate", "entrance"], "correctAnswer": 1 },
  { "id": 237, "word": "门口", "pinyin": "ménkǒu", "english": "doorway; entrance", "options": ["doorway; entrance", "corridor", "path", "gate"], "correctAnswer": 0 },
  { "id": 238, "word": "门票", "pinyin": "ménpiào", "english": "ticket (entrance)", "options": ["ticket (entrance)", "bus pass", "receipt", "permit"], "correctAnswer": 0 },
  { "id": 239, "word": "们", "pinyin": "men", "english": "plural suffix", "options": ["people", "plural suffix", "friends", "group"], "correctAnswer": 1 },
  { "id": 240, "word": "米饭", "pinyin": "mǐfàn", "english": "rice (cooked)", "options": ["rice (cooked)", "bread", "meal", "noodles"], "correctAnswer": 0 },
  { "id": 241, "word": "面包", "pinyin": "miànbāo", "english": "bread", "options": ["noodles", "bread", "rice", "cake"], "correctAnswer": 1 },
  { "id": 242, "word": "面条儿", "pinyin": "miàntiáor", "english": "noodles", "options": ["rice", "bread", "noodles", "soup"], "correctAnswer": 2 },
  { "id": 243, "word": "名字", "pinyin": "míngzi", "english": "name", "options": ["title", "word", "name", "nickname"], "correctAnswer": 2 },
  { "id": 244, "word": "明白", "pinyin": "míngbái", "english": "to understand", "options": ["to think", "to realize", "to understand", "to guess"], "correctAnswer": 2 },
  { "id": 245, "word": "明年", "pinyin": "míngnián", "english": "next year", "options": ["this year", "last year", "next year", "the year before"], "correctAnswer": 2 },
  { "id": 246, "word": "明天", "pinyin": "míngtiān", "english": "tomorrow", "options": ["today", "tomorrow", "yesterday", "morning"], "correctAnswer": 1 },
  { "id": 247, "word": "拿", "pinyin": "ná", "english": "to take; to hold", "options": ["to grab", "to carry", "to take; to hold", "to lift"], "correctAnswer": 2 },
  { "id": 248, "word": "哪", "pinyin": "nǎ", "english": "which", "options": ["who", "where", "which", "what"], "correctAnswer": 2 },
  { "id": 249, "word": "哪儿", "pinyin": "nǎr", "english": "where", "options": ["where", "who", "which", "how"], "correctAnswer": 0 },
  { "id": 250, "word": "哪些", "pinyin": "nǎxiē", "english": "which (plural)", "options": ["which one", "what", "where", "which (plural)"], "correctAnswer": 3 },

{ "id": 251, "word": "那", "pinyin": "nà", "english": "that", "options": ["this", "those", "then", "that"], "correctAnswer": 3 },
{ "id": 252, "word": "那边", "pinyin": "nàbian", "english": "there", "options": ["here", "over there", "there", "where"], "correctAnswer": 2 },
{ "id": 253, "word": "那儿", "pinyin": "nàr", "english": "there", "options": ["here", "there", "everywhere", "somewhere"], "correctAnswer": 1 },
{ "id": 254, "word": "那些", "pinyin": "nàxiē", "english": "those", "options": ["these", "that", "those", "some"], "correctAnswer": 2 },
{ "id": 255, "word": "奶", "pinyin": "nǎi", "english": "milk", "options": ["milk", "butter", "cream", "juice"], "correctAnswer": 0 },
{ "id": 256, "word": "奶奶", "pinyin": "nǎinai", "english": "grandmother", "options": ["grandfather", "aunt", "grandmother", "mother"], "correctAnswer": 2 },
{ "id": 257, "word": "男", "pinyin": "nán", "english": "male", "options": ["male", "female", "boy", "man"], "correctAnswer": 0 },
{ "id": 258, "word": "男孩儿", "pinyin": "nánháir", "english": "boy", "options": ["girl", "boy", "baby", "man"], "correctAnswer": 1 },
{ "id": 259, "word": "男朋友", "pinyin": "nán péngyǒu", "english": "boyfriend", "options": ["husband", "male friend", "boyfriend", "partner"], "correctAnswer": 2 },
{ "id": 260, "word": "男人", "pinyin": "nánrén", "english": "man", "options": ["man", "boy", "gentleman", "husband"], "correctAnswer": 0 },
{ "id": 261, "word": "男生", "pinyin": "nánshēng", "english": "boy student", "options": ["girl student", "boy", "boy student", "male classmate"], "correctAnswer": 2 },
{ "id": 262, "word": "南", "pinyin": "nán", "english": "south", "options": ["north", "east", "west", "south"], "correctAnswer": 3 },
{ "id": 263, "word": "南边", "pinyin": "nánbian", "english": "south side", "options": ["east side", "south side", "north side", "left side"], "correctAnswer": 1 },
{ "id": 264, "word": "难", "pinyin": "nán", "english": "difficult", "options": ["simple", "hard", "easy", "difficult"], "correctAnswer": 3 },
{ "id": 265, "word": "呢", "pinyin": "ne", "english": "modal particle", "options": ["question particle", "modal particle", "tone particle", "soft particle"], "correctAnswer": 1 },
{ "id": 266, "word": "能", "pinyin": "néng", "english": "can", "options": ["should", "can", "might", "must"], "correctAnswer": 1 },
{ "id": 267, "word": "你", "pinyin": "nǐ", "english": "you", "options": ["me", "your", "they", "you"], "correctAnswer": 3 },
{ "id": 268, "word": "你们", "pinyin": "nǐmen", "english": "you (plural)", "options": ["we", "us", "you all", "you (plural)"], "correctAnswer": 3 },
{ "id": 269, "word": "年", "pinyin": "nián", "english": "year", "options": ["month", "week", "year", "day"], "correctAnswer": 2 },
{ "id": 270, "word": "您", "pinyin": "nín", "english": "you (polite)", "options": ["he", "you (polite)", "they", "she"], "correctAnswer": 1 },
{ "id": 271, "word": "牛奶", "pinyin": "niúnǎi", "english": "milk", "options": ["cream", "milk", "juice", "coffee"], "correctAnswer": 1 },
{ "id": 272, "word": "女", "pinyin": "nǚ", "english": "female", "options": ["woman", "female", "lady", "girl"], "correctAnswer": 1 },
{ "id": 273, "word": "女儿", "pinyin": "nǚ'ér", "english": "daughter", "options": ["son", "niece", "daughter", "girl"], "correctAnswer": 2 },
{ "id": 274, "word": "女孩儿", "pinyin": "nǚháir", "english": "girl", "options": ["woman", "girl", "lady", "child"], "correctAnswer": 1 },
{ "id": 275, "word": "女朋友", "pinyin": "nǚ péngyǒu", "english": "girlfriend", "options": ["wife", "girlfriend", "lady friend", "female friend"], "correctAnswer": 1 },
{ "id": 276, "word": "女人", "pinyin": "nǚrén", "english": "woman", "options": ["lady", "girl", "woman", "aunt"], "correctAnswer": 2 },
{ "id": 277, "word": "女生", "pinyin": "nǚshēng", "english": "girl student", "options": ["female student", "girl student", "young girl", "schoolgirl"], "correctAnswer": 1 },
{ "id": 278, "word": "旁边", "pinyin": "pángbiān", "english": "next to", "options": ["beside", "close to", "next to", "near"], "correctAnswer": 2 },
{ "id": 279, "word": "跑", "pinyin": "pǎo", "english": "to run", "options": ["to walk", "to jump", "to run", "to move"], "correctAnswer": 2 },
{ "id": 280, "word": "朋友", "pinyin": "péngyǒu", "english": "friend", "options": ["partner", "colleague", "friend", "mate"], "correctAnswer": 2 },
{ "id": 281, "word": "票", "pinyin": "piào", "english": "ticket", "options": ["ticket", "note", "bill", "card"], "correctAnswer": 0 },
{ "id": 282, "word": "七", "pinyin": "qī", "english": "seven", "options": ["six", "eight", "seven", "nine"], "correctAnswer": 2 },
{ "id": 283, "word": "起", "pinyin": "qǐ", "english": "to rise", "options": ["to get up", "to begin", "to rise", "to stand"], "correctAnswer": 2 },
{ "id": 284, "word": "起床", "pinyin": "qǐchuáng", "english": "to get up", "options": ["to sleep", "to lie down", "to get up", "to rise"], "correctAnswer": 2 },
{ "id": 285, "word": "起来", "pinyin": "qǐlái", "english": "to get up", "options": ["to stand", "to move", "to wake up", "to get up"], "correctAnswer": 3 },
{ "id": 286, "word": "汽车", "pinyin": "qìchē", "english": "car", "options": ["train", "bus", "car", "bicycle"], "correctAnswer": 2 },
{ "id": 287, "word": "前", "pinyin": "qián", "english": "before", "options": ["front", "after", "before", "first"], "correctAnswer": 2 },
{ "id": 288, "word": "前边", "pinyin": "qiánbian", "english": "front", "options": ["front", "back", "ahead", "before"], "correctAnswer": 0 },
{ "id": 289, "word": "前天", "pinyin": "qiántiān", "english": "the day before yesterday", "options": ["yesterday", "tomorrow", "today", "the day before yesterday"], "correctAnswer": 3 },
{ "id": 290, "word": "钱", "pinyin": "qián", "english": "money", "options": ["cash", "coin", "funds", "money"], "correctAnswer": 3 },
{ "id": 291, "word": "钱包", "pinyin": "qiánbāo", "english": "wallet", "options": ["wallet", "purse", "bag", "case"], "correctAnswer": 0 },
{ "id": 292, "word": "请", "pinyin": "qǐng", "english": "please", "options": ["thank you", "excuse me", "please", "sorry"], "correctAnswer": 2 },
{ "id": 293, "word": "请假", "pinyin": "qǐngjià", "english": "to ask for leave", "options": ["to rest", "to leave", "to ask for leave", "to request time off"], "correctAnswer": 2 },
{ "id": 294, "word": "请进", "pinyin": "qǐng jìn", "english": "please come in", "options": ["please go out", "please enter", "please come in", "please leave"], "correctAnswer": 2 },
{ "id": 295, "word": "请问", "pinyin": "qǐngwèn", "english": "excuse me", "options": ["please say", "may I ask", "excuse me", "sorry"], "correctAnswer": 2 },
{ "id": 296, "word": "请坐", "pinyin": "qǐng zuò", "english": "please sit down", "options": ["please stand", "please sit down", "please wait", "please come"], "correctAnswer": 1 },
{ "id": 297, "word": "球", "pinyin": "qiú", "english": "ball", "options": ["round", "ball", "circle", "sphere"], "correctAnswer": 1 },
{ "id": 298, "word": "去", "pinyin": "qù", "english": "to go", "options": ["to come", "to go", "to move", "to reach"], "correctAnswer": 1 },
{ "id": 299, "word": "去年", "pinyin": "qùnián", "english": "last year", "options": ["next year", "last year", "this year", "year before"], "correctAnswer": 1 },
{ "id": 300, "word": "热", "pinyin": "rè", "english": "hot", "options": ["cold", "warm", "hot", "cool"], "correctAnswer": 2 },

  { "id": 301, "word": "人", "pinyin": "rén", "english": "person; people", "options": ["man", "human", "person; people", "crowd"], "correctAnswer": 2 },
  { "id": 302, "word": "认识", "pinyin": "rènshi", "english": "to know", "options": ["to meet", "to recognize", "to know", "to remember"], "correctAnswer": 2 },
  { "id": 303, "word": "认真", "pinyin": "rènzhēn", "english": "serious", "options": ["careful", "honest", "strict", "serious"], "correctAnswer": 3 },
  { "id": 304, "word": "日", "pinyin": "rì", "english": "day", "options": ["date", "sun", "day", "month"], "correctAnswer": 2 },
  { "id": 305, "word": "日期", "pinyin": "rìqī", "english": "date", "options": ["calendar", "day", "time", "date"], "correctAnswer": 3 },
  { "id": 306, "word": "肉", "pinyin": "ròu", "english": "meat", "options": ["meat", "fish", "egg", "chicken"], "correctAnswer": 0 },
  { "id": 307, "word": "三", "pinyin": "sān", "english": "three", "options": ["two", "three", "four", "five"], "correctAnswer": 1 },
  { "id": 308, "word": "山", "pinyin": "shān", "english": "mountain", "options": ["river", "hill", "mountain", "valley"], "correctAnswer": 2 },
  { "id": 309, "word": "商场", "pinyin": "shāngchǎng", "english": "mall", "options": ["shop", "supermarket", "market", "mall"], "correctAnswer": 3 },
  { "id": 310, "word": "商店", "pinyin": "shāngdiàn", "english": "shop", "options": ["mall", "shop", "market", "store"], "correctAnswer": 1 },
  { "id": 311, "word": "上", "pinyin": "shàng", "english": "on", "options": ["in", "under", "above", "on"], "correctAnswer": 3 },
  { "id": 312, "word": "上班", "pinyin": "shàngbān", "english": "to go to work", "options": ["to rest", "to work", "to go to work", "to study"], "correctAnswer": 2 },
  { "id": 313, "word": "上边", "pinyin": "shàngbian", "english": "above", "options": ["top", "on", "above", "over"], "correctAnswer": 2 },
  { "id": 314, "word": "上车", "pinyin": "shàng chē", "english": "to get on a vehicle", "options": ["to take a ride", "to enter", "to get on a vehicle", "to stop the car"], "correctAnswer": 2 },
  { "id": 315, "word": "上次", "pinyin": "shàng cì", "english": "last time", "options": ["before", "last week", "last time", "previous"], "correctAnswer": 2 },
  { "id": 316, "word": "上课", "pinyin": "shàngkè", "english": "to go to class", "options": ["to learn", "to attend class", "to go to class", "to study"], "correctAnswer": 2 },
  { "id": 317, "word": "上网", "pinyin": "shàngwǎng", "english": "to go online", "options": ["to browse", "to surf", "to go online", "to use computer"], "correctAnswer": 2 },
  { "id": 318, "word": "上午", "pinyin": "shàngwǔ", "english": "morning", "options": ["daytime", "morning", "noon", "evening"], "correctAnswer": 1 },
  { "id": 319, "word": "上学", "pinyin": "shàngxué", "english": "to go to school", "options": ["to attend school", "to start school", "to go to school", "to study"], "correctAnswer": 2 },
  { "id": 320, "word": "少", "pinyin": "shǎo", "english": "few; little", "options": ["few; little", "less", "tiny", "short"], "correctAnswer": 0 },
  { "id": 321, "word": "谁", "pinyin": "shéi", "english": "who", "options": ["where", "which", "who", "what"], "correctAnswer": 2 },
  { "id": 322, "word": "身上", "pinyin": "shēnshang", "english": "on one's body", "options": ["on the body", "inside the body", "on one's body", "above the body"], "correctAnswer": 2 },
  { "id": 323, "word": "身体", "pinyin": "shēntǐ", "english": "body", "options": ["body", "health", "figure", "form"], "correctAnswer": 0 },
  { "id": 324, "word": "什么", "pinyin": "shénme", "english": "what", "options": ["who", "when", "where", "what"], "correctAnswer": 3 },
  { "id": 325, "word": "生病", "pinyin": "shēngbìng", "english": "to be sick", "options": ["to feel bad", "to get sick", "to be sick", "to rest"], "correctAnswer": 2 },
  { "id": 326, "word": "生气", "pinyin": "shēngqì", "english": "to be angry", "options": ["to get sad", "to be angry", "to be tired", "to be upset"], "correctAnswer": 1 },
  { "id": 327, "word": "生日", "pinyin": "shēngrì", "english": "birthday", "options": ["holiday", "birthday", "celebration", "festival"], "correctAnswer": 1 },
  { "id": 328, "word": "十", "pinyin": "shí", "english": "ten", "options": ["nine", "eight", "ten", "eleven"], "correctAnswer": 2 },
  { "id": 329, "word": "时候", "pinyin": "shíhou", "english": "time", "options": ["moment", "period", "time", "hour"], "correctAnswer": 2 },
  { "id": 330, "word": "时间", "pinyin": "shíjiān", "english": "time", "options": ["moment", "clock", "time", "duration"], "correctAnswer": 2 },
  { "id": 331, "word": "事", "pinyin": "shì", "english": "thing", "options": ["matter", "thing", "event", "issue"], "correctAnswer": 1 },
  { "id": 332, "word": "试", "pinyin": "shì", "english": "to test; to try", "options": ["to test; to try", "to check", "to examine", "to attempt"], "correctAnswer": 0 },
  { "id": 333, "word": "是", "pinyin": "shì", "english": "to be", "options": ["to do", "to have", "to be", "to exist"], "correctAnswer": 2 },
  { "id": 334, "word": "是不是", "pinyin": "shì búshì", "english": "yes or no?", "options": ["right?", "is it?", "yes or no?", "okay?"], "correctAnswer": 2 },
  { "id": 335, "word": "手", "pinyin": "shǒu", "english": "hand", "options": ["finger", "hand", "arm", "palm"], "correctAnswer": 1 },
  { "id": 336, "word": "手机", "pinyin": "shǒujī", "english": "mobile phone", "options": ["cellphone", "mobile", "telephone", "mobile phone"], "correctAnswer": 3 },
  { "id": 337, "word": "书", "pinyin": "shū", "english": "book", "options": ["book", "magazine", "page", "novel"], "correctAnswer": 0 },
  { "id": 338, "word": "书包", "pinyin": "shūbāo", "english": "schoolbag", "options": ["bag", "schoolbag", "backpack", "purse"], "correctAnswer": 1 },
  { "id": 339, "word": "书店", "pinyin": "shūdiàn", "english": "bookstore", "options": ["library", "bookstore", "shop", "stationery"], "correctAnswer": 1 },
  { "id": 340, "word": "树", "pinyin": "shù", "english": "tree", "options": ["tree", "plant", "wood", "branch"], "correctAnswer": 0 },
  { "id": 341, "word": "水", "pinyin": "shuǐ", "english": "water", "options": ["juice", "liquid", "water", "drink"], "correctAnswer": 2 },
  { "id": 342, "word": "水果", "pinyin": "shuǐguǒ", "english": "fruit", "options": ["fruit", "juice", "vegetable", "snack"], "correctAnswer": 0 },
  { "id": 343, "word": "睡", "pinyin": "shuì", "english": "to sleep", "options": ["to nap", "to dream", "to sleep", "to lie down"], "correctAnswer": 2 },
  { "id": 344, "word": "睡觉", "pinyin": "shuìjiào", "english": "to go to bed", "options": ["to rest", "to sleep", "to go to bed", "to lie down"], "correctAnswer": 2 },
  { "id": 345, "word": "说", "pinyin": "shuō", "english": "to say", "options": ["to speak", "to tell", "to say", "to chat"], "correctAnswer": 2 },
  { "id": 346, "word": "说话", "pinyin": "shuōhuà", "english": "to speak", "options": ["to say", "to talk", "to speak", "to tell"], "correctAnswer": 2 },
  { "id": 347, "word": "四", "pinyin": "sì", "english": "four", "options": ["three", "five", "four", "two"], "correctAnswer": 2 },
  { "id": 348, "word": "送", "pinyin": "sòng", "english": "to give away", "options": ["to present", "to send", "to gift", "to give away"], "correctAnswer": 3 },
  { "id": 349, "word": "岁", "pinyin": "suì", "english": "year (of age)", "options": ["year", "old", "age", "year (of age)"], "correctAnswer": 3 },
  { "id": 350, "word": "他", "pinyin": "tā", "english": "he", "options": ["he", "him", "man", "boy"], "correctAnswer": 0 },
  
  { "id": 351, "word": "他们", "pinyin": "tāmen", "english": "they (male/mixed group)", "options": ["she", "he", "they (male/mixed group)", "we"], "correctAnswer": 2 },
  { "id": 352, "word": "她", "pinyin": "tā", "english": "she", "options": ["he", "she", "her", "woman"], "correctAnswer": 1 },
  { "id": 353, "word": "她们", "pinyin": "tāmen", "english": "they (female group)", "options": ["they", "them", "they (female group)", "girls"], "correctAnswer": 2 },
  { "id": 354, "word": "太", "pinyin": "tài", "english": "too; extremely", "options": ["very", "quite", "too; extremely", "so"], "correctAnswer": 2 },
  { "id": 355, "word": "天", "pinyin": "tiān", "english": "day", "options": ["sky", "heaven", "day", "sun"], "correctAnswer": 2 },
  { "id": 356, "word": "天气", "pinyin": "tiānqì", "english": "weather", "options": ["season", "air", "climate", "weather"], "correctAnswer": 3 },
  { "id": 357, "word": "听", "pinyin": "tīng", "english": "to listen", "options": ["to hear", "to listen", "to speak", "to say"], "correctAnswer": 1 },
  { "id": 358, "word": "听到", "pinyin": "tīng dào", "english": "to hear", "options": ["to notice", "to listen", "to hear", "to find out"], "correctAnswer": 2 },
  { "id": 359, "word": "听见", "pinyin": "tīngjiàn", "english": "to hear", "options": ["to listen", "to hear", "to sense", "to overhear"], "correctAnswer": 1 },
  { "id": 360, "word": "听写", "pinyin": "tīngxiě", "english": "dictation", "options": ["writing", "note-taking", "dictation", "listening test"], "correctAnswer": 2 },
  { "id": 361, "word": "同学", "pinyin": "tóngxué", "english": "classmate", "options": ["student", "peer", "friend", "classmate"], "correctAnswer": 3 },
  { "id": 362, "word": "图书馆", "pinyin": "túshūguǎn", "english": "library", "options": ["bookshop", "study hall", "library", "reading room"], "correctAnswer": 2 },
  { "id": 363, "word": "外", "pinyin": "wài", "english": "outer; outside", "options": ["inside", "outer; outside", "outdoor", "external"], "correctAnswer": 1 },
  { "id": 364, "word": "外边", "pinyin": "wàibian", "english": "outside", "options": ["outer", "outside", "outdoor", "beyond"], "correctAnswer": 1 },
  { "id": 365, "word": "外国", "pinyin": "wàiguó", "english": "foreign country", "options": ["foreign place", "overseas", "foreign country", "abroad"], "correctAnswer": 2 },
  { "id": 366, "word": "外语", "pinyin": "wàiyǔ", "english": "foreign language", "options": ["language", "foreign language", "dialect", "tongue"], "correctAnswer": 1 },
  { "id": 367, "word": "玩儿", "pinyin": "wánr", "english": "to play", "options": ["to have fun", "to act", "to play", "to joke"], "correctAnswer": 2 },
  { "id": 368, "word": "晚", "pinyin": "wǎn", "english": "late", "options": ["evening", "delayed", "late", "night"], "correctAnswer": 2 },
  { "id": 369, "word": "晚饭", "pinyin": "wǎnfàn", "english": "dinner", "options": ["supper", "lunch", "dinner", "meal"], "correctAnswer": 2 },
  { "id": 370, "word": "晚上", "pinyin": "wǎnshang", "english": "night", "options": ["evening", "night", "midnight", "dark"], "correctAnswer": 1 },
  { "id": 371, "word": "网上", "pinyin": "wǎngshàng", "english": "online", "options": ["internet", "on web", "online", "on the net"], "correctAnswer": 2 },
  { "id": 372, "word": "网友", "pinyin": "wǎngyǒu", "english": "netizen", "options": ["online friend", "user", "netizen", "webmate"], "correctAnswer": 2 },
  { "id": 373, "word": "忘", "pinyin": "wàng", "english": "to forget", "options": ["to lose", "to miss", "to forget", "to ignore"], "correctAnswer": 2 },
  { "id": 374, "word": "忘记", "pinyin": "wàngjì", "english": "to forget", "options": ["to forget", "to erase", "to ignore", "to overlook"], "correctAnswer": 0 },
  { "id": 375, "word": "问", "pinyin": "wèn", "english": "to ask", "options": ["to say", "to tell", "to ask", "to speak"], "correctAnswer": 2 },
  { "id": 376, "word": "我", "pinyin": "wǒ", "english": "I; me", "options": ["I; me", "myself", "mine", "we"], "correctAnswer": 0 },
  { "id": 377, "word": "我们", "pinyin": "wǒmen", "english": "we; us", "options": ["they", "you", "we; us", "ourselves"], "correctAnswer": 2 },
  { "id": 378, "word": "五", "pinyin": "wǔ", "english": "five", "options": ["four", "five", "six", "three"], "correctAnswer": 1 },
  { "id": 379, "word": "午饭", "pinyin": "wǔfàn", "english": "lunch", "options": ["lunch", "brunch", "breakfast", "meal"], "correctAnswer": 0 },
  { "id": 380, "word": "西", "pinyin": "xī", "english": "west", "options": ["east", "north", "south", "west"], "correctAnswer": 3 },
  { "id": 381, "word": "西边", "pinyin": "xībian", "english": "west side", "options": ["east side", "south side", "north side", "west side"], "correctAnswer": 3 },
  { "id": 382, "word": "洗", "pinyin": "xǐ", "english": "to wash", "options": ["to clean", "to rinse", "to wash", "to wipe"], "correctAnswer": 2 },
  { "id": 383, "word": "洗手间", "pinyin": "xǐshǒujiān", "english": "restroom", "options": ["bathroom", "restroom", "toilet", "washroom"], "correctAnswer": 1 },
  { "id": 384, "word": "喜欢", "pinyin": "xǐhuan", "english": "to like", "options": ["to love", "to prefer", "to like", "to enjoy"], "correctAnswer": 2 },
  { "id": 385, "word": "下", "pinyin": "xià", "english": "down; next; to get off", "options": ["under", "below", "down; next; to get off", "after"], "correctAnswer": 2 },
  { "id": 386, "word": "下班", "pinyin": "xiàbān", "english": "to get off work", "options": ["to leave", "to rest", "to get off work", "to go home"], "correctAnswer": 2 },
  { "id": 387, "word": "下边", "pinyin": "xiàbian", "english": "below", "options": ["bottom", "under", "below", "beneath"], "correctAnswer": 2 },
  { "id": 388, "word": "下车", "pinyin": "xià chē", "english": "to get off a vehicle", "options": ["to go down", "to stop", "to get off a vehicle", "to board"], "correctAnswer": 2 },
  { "id": 389, "word": "下次", "pinyin": "xià cì", "english": "next time", "options": ["again", "next time", "later", "afterward"], "correctAnswer": 1 },
  { "id": 390, "word": "下课", "pinyin": "xiàkè", "english": "to finish class", "options": ["to stop learning", "to dismiss", "to finish class", "to end school"], "correctAnswer": 2 },
  { "id": 391, "word": "下午", "pinyin": "xiàwǔ", "english": "afternoon", "options": ["noon", "evening", "afternoon", "morning"], "correctAnswer": 2 },
  { "id": 392, "word": "下雨", "pinyin": "xià yǔ", "english": "to rain", "options": ["to drizzle", "to rain", "to storm", "to snow"], "correctAnswer": 1 },
  { "id": 393, "word": "先", "pinyin": "xiān", "english": "first", "options": ["early", "before", "first", "front"], "correctAnswer": 2 },
  { "id": 394, "word": "先生", "pinyin": "xiānsheng", "english": "Mr", "options": ["sir", "Mr", "man", "teacher"], "correctAnswer": 1 },
  { "id": 395, "word": "现在", "pinyin": "xiànzài", "english": "now", "options": ["today", "present", "now", "soon"], "correctAnswer": 2 },
  { "id": 396, "word": "想", "pinyin": "xiǎng", "english": "to want", "options": ["to wish", "to think", "to want", "to hope"], "correctAnswer": 2 },
  { "id": 397, "word": "小", "pinyin": "xiǎo", "english": "small", "options": ["tiny", "little", "small", "short"], "correctAnswer": 2 },
  { "id": 398, "word": "小孩儿", "pinyin": "xiǎoháir", "english": "child", "options": ["kid", "youngster", "child", "baby"], "correctAnswer": 2 },
  { "id": 399, "word": "小姐", "pinyin": "xiǎojiě", "english": "Miss", "options": ["lady", "Miss", "madam", "girl"], "correctAnswer": 1 },
  { "id": 400, "word": "小朋友", "pinyin": "xiǎopéngyǒu", "english": "child", "options": ["child", "kid", "baby", "little one"], "correctAnswer": 0 },
  
  { "id": 401, "word": "小时", "pinyin": "xiǎoshí", "english": "hour", "options": ["hour", "minute", "second", "day"], "correctAnswer": 0 },
  { "id": 402, "word": "小学", "pinyin": "xiǎoxué", "english": "primary school", "options": ["primary school", "high school", "university", "college"], "correctAnswer": 0 },
  { "id": 403, "word": "小学生", "pinyin": "xiǎoxuéshēng", "english": "primary school student", "options": ["primary school student", "university student", "teacher", "pupil"], "correctAnswer": 0 },
  { "id": 404, "word": "笑", "pinyin": "xiào", "english": "to laugh", "options": ["to laugh", "to cry", "to smile", "to speak"], "correctAnswer": 0 },
  { "id": 405, "word": "写", "pinyin": "xiě", "english": "to write", "options": ["to write", "to read", "to draw", "to listen"], "correctAnswer": 0 },
  { "id": 406, "word": "谢谢", "pinyin": "xièxie", "english": "thank you", "options": ["thank you", "sorry", "hello", "goodbye"], "correctAnswer": 0 },
  { "id": 407, "word": "新", "pinyin": "xīn", "english": "new", "options": ["new", "old", "fresh", "modern"], "correctAnswer": 0 },
  { "id": 408, "word": "新年", "pinyin": "xīnnián", "english": "new year", "options": ["new year", "holiday", "birthday", "festival"], "correctAnswer": 0 },
  { "id": 409, "word": "星期", "pinyin": "xīngqī", "english": "week", "options": ["week", "month", "day", "year"], "correctAnswer": 0 },
  { "id": 410, "word": "星期日", "pinyin": "xīngqīrì", "english": "sunday", "options": ["sunday", "saturday", "friday", "monday"], "correctAnswer": 0 },
  { "id": 411, "word": "星期天", "pinyin": "xīngqītiān", "english": "sunday", "options": ["sunday", "saturday", "friday", "monday"], "correctAnswer": 0 },
  { "id": 412, "word": "行", "pinyin": "xíng", "english": "okay", "options": ["okay", "no", "good", "bad"], "correctAnswer": 0 },
  { "id": 413, "word": "休息", "pinyin": "xiūxi", "english": "to rest", "options": ["to rest", "to sleep", "to sit", "to wait"], "correctAnswer": 0 },
  { "id": 414, "word": "学", "pinyin": "xué", "english": "to learn", "options": ["to learn", "to teach", "to read", "to listen"], "correctAnswer": 0 },
  { "id": 415, "word": "学生", "pinyin": "xuésheng", "english": "student", "options": ["student", "teacher", "worker", "child"], "correctAnswer": 0 },
  { "id": 416, "word": "学习", "pinyin": "xuéxí", "english": "to learn", "options": ["to learn", "to write", "to draw", "to speak"], "correctAnswer": 0 },
  { "id": 417, "word": "学校", "pinyin": "xuéxiào", "english": "school", "options": ["school", "class", "office", "library"], "correctAnswer": 0 },
  { "id": 418, "word": "学院", "pinyin": "xuéyuàn", "english": "college", "options": ["college", "school", "library", "department"], "correctAnswer": 0 },
  { "id": 419, "word": "要", "pinyin": "yào", "english": "to want", "options": ["to want", "to have", "to go", "to take"], "correctAnswer": 0 },
  { "id": 420, "word": "爷爷", "pinyin": "yéye", "english": "grandfather", "options": ["grandfather", "father", "uncle", "elder brother"], "correctAnswer": 0 },
  { "id": 421, "word": "也", "pinyin": "yě", "english": "also", "options": ["also", "but", "and", "even"], "correctAnswer": 0 },
  { "id": 422, "word": "页", "pinyin": "yè", "english": "page", "options": ["page", "book", "paper", "sheet"], "correctAnswer": 0 },
  { "id": 423, "word": "一", "pinyin": "yī", "english": "one", "options": ["one", "two", "three", "first"], "correctAnswer": 0 },
  { "id": 424, "word": "衣服", "pinyin": "yīfu", "english": "clothes", "options": ["clothes", "shoes", "hat", "dress"], "correctAnswer": 0 },
  { "id": 425, "word": "医生", "pinyin": "yīshēng", "english": "doctor", "options": ["doctor", "nurse", "teacher", "patient"], "correctAnswer": 0 },
  { "id": 426, "word": "医院", "pinyin": "yīyuàn", "english": "hospital", "options": ["hospital", "clinic", "pharmacy", "school"], "correctAnswer": 0 },
  { "id": 427, "word": "一半", "pinyin": "yībàn", "english": "half", "options": ["half", "part", "some", "few"], "correctAnswer": 0 },
  { "id": 428, "word": "一会儿", "pinyin": "yīhuìr", "english": "a moment", "options": ["a moment", "a long time", "soon", "afterwards"], "correctAnswer": 0 },
  { "id": 429, "word": "一块儿", "pinyin": "yīkuàir", "english": "together", "options": ["together", "apart", "near", "far"], "correctAnswer": 0 },
  { "id": 430, "word": "一下儿", "pinyin": "yīxiàr", "english": "a while", "options": ["a while", "later", "soon", "now"], "correctAnswer": 0 },
  { "id": 431, "word": "一样", "pinyin": "yīyàng", "english": "the same", "options": ["the same", "different", "similar", "close"], "correctAnswer": 0 },
  { "id": 432, "word": "一边", "pinyin": "yībiān", "english": "one side", "options": ["one side", "other side", "middle", "corner"], "correctAnswer": 0 },
  { "id": 433, "word": "一点儿", "pinyin": "yīdiǎnr", "english": "a little", "options": ["a little", "much", "many", "some"], "correctAnswer": 0 },
  { "id": 434, "word": "一起", "pinyin": "yīqǐ", "english": "together", "options": ["together", "alone", "apart", "near"], "correctAnswer": 0 },
  { "id": 435, "word": "一些", "pinyin": "yīxiē", "english": "some", "options": ["some", "many", "few", "a lot"], "correctAnswer": 0 },
  { "id": 436, "word": "用", "pinyin": "yòng", "english": "to use", "options": ["to use", "to make", "to have", "to do"], "correctAnswer": 0 },
  { "id": 437, "word": "有", "pinyin": "yǒu", "english": "to have", "options": ["to have", "to get", "to want", "to see"], "correctAnswer": 0 },
  { "id": 438, "word": "有的", "pinyin": "yǒude", "english": "some", "options": ["some", "few", "many", "all"], "correctAnswer": 0 },
  { "id": 439, "word": "有名", "pinyin": "yǒumíng", "english": "famous", "options": ["famous", "rich", "popular", "known"], "correctAnswer": 0 },
  { "id": 440, "word": "有时候", "pinyin": "yǒu shíhou", "english": "sometimes", "options": ["sometimes", "always", "never", "often"], "correctAnswer": 0 },
  { "id": 441, "word": "有(一)些", "pinyin": "yǒu (yī) xiē", "english": "there are some", "options": ["there are some", "there is one", "none", "few"], "correctAnswer": 0 },
  { "id": 442, "word": "有用", "pinyin": "yǒuyòng", "english": "it works", "options": ["it works", "it fails", "it is broken", "it’s old"], "correctAnswer": 0 },
  { "id": 443, "word": "右", "pinyin": "yòu", "english": "right (direction)", "options": ["right", "left", "up", "down"], "correctAnswer": 0 },
  { "id": 444, "word": "右边", "pinyin": "yòubiān", "english": "right side", "options": ["right side", "left side", "front", "back"], "correctAnswer": 0 },
  { "id": 445, "word": "雨", "pinyin": "yǔ", "english": "rain", "options": ["rain", "snow", "wind", "cloud"], "correctAnswer": 0 },
  { "id": 446, "word": "元", "pinyin": "yuán", "english": "yuan", "options": ["yuan", "dollar", "pound", "euro"], "correctAnswer": 0 },
  { "id": 447, "word": "远", "pinyin": "yuǎn", "english": "far", "options": ["far", "near", "close", "short"], "correctAnswer": 0 },
  { "id": 448, "word": "月", "pinyin": "yuè", "english": "month", "options": ["month", "day", "year", "week"], "correctAnswer": 0 },
  { "id": 449, "word": "再", "pinyin": "zài", "english": "again", "options": ["again", "once", "always", "soon"], "correctAnswer": 0 },
  { "id": 450, "word": "再见", "pinyin": "zàijiàn", "english": "goodbye", "options": ["goodbye", "hello", "thanks", "please"], "correctAnswer": 0 },
  
  { "id": 451, "word": "在", "pinyin": "zài", "english": "in/at/on", "options": ["in/at/on", "under", "beside", "between"], "correctAnswer": 0 },
  { "id": 452, "word": "在家", "pinyin": "zàijiā", "english": "at home", "options": ["at home", "at school", "outside", "in office"], "correctAnswer": 0 },
  { "id": 453, "word": "早", "pinyin": "zǎo", "english": "early", "options": ["early", "late", "soon", "on time"], "correctAnswer": 0 },
  { "id": 454, "word": "早饭", "pinyin": "zǎofàn", "english": "breakfast", "options": ["breakfast", "lunch", "dinner", "snack"], "correctAnswer": 0 },
  { "id": 455, "word": "早上", "pinyin": "zǎoshang", "english": "morning", "options": ["morning", "evening", "noon", "night"], "correctAnswer": 0 },
  { "id": 456, "word": "怎么", "pinyin": "zěnme", "english": "how?", "options": ["how?", "what?", "why?", "where?"], "correctAnswer": 0 },
  { "id": 457, "word": "站", "pinyin": "zhàn", "english": "station", "options": ["station", "stop", "place", "corner"], "correctAnswer": 0 },
  { "id": 458, "word": "找", "pinyin": "zhǎo", "english": "to look for", "options": ["to look for", "to find", "to lose", "to see"], "correctAnswer": 0 },
  { "id": 459, "word": "找到", "pinyin": "zhǎodào", "english": "to find", "options": ["to find", "to look for", "to lose", "to search"], "correctAnswer": 0 },
  { "id": 460, "word": "这", "pinyin": "zhè", "english": "this", "options": ["this", "that", "these", "those"], "correctAnswer": 0 },
  { "id": 461, "word": "这边", "pinyin": "zhèbiān", "english": "here", "options": ["here", "there", "over there", "beside"], "correctAnswer": 0 },
  { "id": 462, "word": "这里", "pinyin": "zhèlǐ", "english": "here", "options": ["here", "there", "inside", "outside"], "correctAnswer": 0 },
  { "id": 463, "word": "这儿", "pinyin": "zhèr", "english": "here", "options": ["here", "there", "near", "away"], "correctAnswer": 0 },
  { "id": 464, "word": "这些", "pinyin": "zhèxiē", "english": "these", "options": ["these", "those", "that", "this"], "correctAnswer": 0 },
  { "id": 465, "word": "着", "pinyin": "zhe", "english": "particle", "options": ["particle", "noun", "verb", "adjective"], "correctAnswer": 0 },
  { "id": 466, "word": "真", "pinyin": "zhēn", "english": "true", "options": ["true", "false", "right", "wrong"], "correctAnswer": 0 },
  { "id": 467, "word": "真的", "pinyin": "zhēnde", "english": "really", "options": ["really", "surely", "maybe", "possibly"], "correctAnswer": 0 },
  { "id": 468, "word": "正", "pinyin": "zhèng", "english": "just (in the process of)", "options": ["just (in the process of)", "already", "before", "after"], "correctAnswer": 0 },
  { "id": 469, "word": "正在", "pinyin": "zhèngzài", "english": "being", "options": ["being", "done", "ready", "finished"], "correctAnswer": 0 },
  { "id": 470, "word": "知道", "pinyin": "zhīdào", "english": "to know", "options": ["to know", "to learn", "to tell", "to hear"], "correctAnswer": 0 },
  { "id": 471, "word": "知识", "pinyin": "zhīshi", "english": "knowledge", "options": ["knowledge", "information", "lesson", "study"], "correctAnswer": 0 },
  { "id": 472, "word": "中", "pinyin": "zhōng", "english": "middle", "options": ["middle", "top", "bottom", "center"], "correctAnswer": 0 },
  { "id": 473, "word": "中国", "pinyin": "Zhōngguó", "english": "China", "options": ["China", "Japan", "Korea", "Asia"], "correctAnswer": 0 },
  { "id": 474, "word": "中间", "pinyin": "zhōngjiān", "english": "intermediate", "options": ["intermediate", "center", "edge", "corner"], "correctAnswer": 0 },
  { "id": 475, "word": "中文", "pinyin": "Zhōngwén", "english": "Chinese", "options": ["Chinese", "English", "Mandarin", "Japanese"], "correctAnswer": 0 },
  { "id": 476, "word": "中午", "pinyin": "zhōngwǔ", "english": "noon", "options": ["noon", "morning", "evening", "midnight"], "correctAnswer": 0 },
  { "id": 477, "word": "中学", "pinyin": "zhōngxué", "english": "middle school", "options": ["middle school", "high school", "college", "primary school"], "correctAnswer": 0 },
  { "id": 478, "word": "中学生", "pinyin": "zhōngxuéshēng", "english": "middle school student", "options": ["middle school student", "college student", "teacher", "primary student"], "correctAnswer": 0 },
  { "id": 479, "word": "重", "pinyin": "zhòng", "english": "heavy", "options": ["heavy", "light", "strong", "deep"], "correctAnswer": 0 },
  { "id": 480, "word": "重要", "pinyin": "zhòngyào", "english": "important", "options": ["important", "urgent", "useful", "simple"], "correctAnswer": 0 },
  { "id": 481, "word": "住", "pinyin": "zhù", "english": "to live", "options": ["to live", "to stay", "to go", "to move"], "correctAnswer": 0 },
  { "id": 482, "word": "准备", "pinyin": "zhǔnbèi", "english": "to prepare", "options": ["to prepare", "to plan", "to do", "to finish"], "correctAnswer": 0 },
  { "id": 483, "word": "桌子", "pinyin": "zhuōzi", "english": "table", "options": ["table", "chair", "bed", "desk"], "correctAnswer": 0 },
  { "id": 484, "word": "字", "pinyin": "zì", "english": "character", "options": ["character", "word", "letter", "sign"], "correctAnswer": 0 },
  { "id": 485, "word": "子", "pinyin": "zǐ", "english": "noun suffix", "options": ["noun suffix", "verb", "adjective", "particle"], "correctAnswer": 0 },
  { "id": 486, "word": "走", "pinyin": "zǒu", "english": "go", "options": ["go", "run", "walk", "leave"], "correctAnswer": 0 },
  { "id": 487, "word": "走路", "pinyin": "zǒulù", "english": "to walk", "options": ["to walk", "to run", "to drive", "to stand"], "correctAnswer": 0 },
  { "id": 488, "word": "最", "pinyin": "zuì", "english": "most", "options": ["most", "least", "some", "very"], "correctAnswer": 0 },
  { "id": 489, "word": "最好", "pinyin": "zuì hǎo", "english": "the best", "options": ["the best", "better", "good", "well"], "correctAnswer": 0 },
  { "id": 490, "word": "最后", "pinyin": "zuìhòu", "english": "last", "options": ["last", "first", "next", "before"], "correctAnswer": 0 },
  { "id": 491, "word": "昨天", "pinyin": "zuótiān", "english": "yesterday", "options": ["yesterday", "today", "tomorrow", "last night"], "correctAnswer": 0 },
  { "id": 492, "word": "左", "pinyin": "zuǒ", "english": "left", "options": ["left", "right", "up", "down"], "correctAnswer": 0 },
  { "id": 493, "word": "左边", "pinyin": "zuǒbian", "english": "left side", "options": ["left side", "right side", "front", "back"], "correctAnswer": 0 },
  { "id": 494, "word": "坐", "pinyin": "zuò", "english": "to sit", "options": ["to sit", "to stand", "to lie", "to stay"], "correctAnswer": 0 },
  { "id": 495, "word": "坐下", "pinyin": "zuò xià", "english": "to sit down", "options": ["to sit down", "to stand up", "to go out", "to lie down"], "correctAnswer": 0 },
  { "id": 496, "word": "做", "pinyin": "zuò", "english": "to do", "options": ["to do", "to make", "to go", "to have"], "correctAnswer": 0 }

]



@words_bp.route('/quiz')
def words_quiz():
    """Render the words quiz page"""
    return render_template('quiz_words.html')

@words_bp.route('/api/quiz-words')
def get_quiz_words():
    """API endpoint to get words for the quiz"""
    try:
        # Get number of questions from request (default 20)
        num_questions = int(request.args.get('count', 20))
        
        # Select random words for the quiz
        quiz_words = random.sample(HSK1_WORDS, min(num_questions, len(HSK1_WORDS)))
        
        # Randomize the position of correct answers
        for word in quiz_words:
            correct_answer = word['options'][word['correctAnswer']]
            random.shuffle(word['options'])
            word['correctAnswer'] = word['options'].index(correct_answer)
        
        return jsonify({
            'success': True,
            'words': quiz_words,
            'total_words': len(HSK1_WORDS),
            'quiz_count': num_questions
        })
        
    except Exception as e:
        return jsonify({
            'success': False,
            'message': f'Error retrieving quiz words: {str(e)}'
        }), 500

@words_bp.route('/api/all-words')
def get_all_words():
    """API endpoint to get all HSK1 words"""
    try:
        return jsonify({
            'success': True,
            'words': HSK1_WORDS
        })
        
    except Exception as e:
        return jsonify({
            'success': False,
            'message': f'Error retrieving words: {str(e)}'
        }), 500

@words_bp.route('/api/next-quiz')
def get_next_quiz():
    """API endpoint to get a new quiz with different words"""
    try:
        # Get previously used word IDs from session
        used_ids = session.get('used_word_ids', [])
        
        # Get available words (not used before)
        available_words = [word for word in HSK1_WORDS if word['id'] not in used_ids]
        
        # If we don't have enough new words, reset and use all words
        num_questions = int(request.args.get('count', 20))
        if len(available_words) < num_questions:
            available_words = HSK1_WORDS.copy()
            used_ids = []
        
        # Select new words
        quiz_words = random.sample(available_words, min(num_questions, len(available_words)))
        
        # Update used word IDs in session
        new_used_ids = used_ids + [word['id'] for word in quiz_words]
        session['used_word_ids'] = new_used_ids
        
        # Randomize the position of correct answers
        for word in quiz_words:
            correct_answer = word['options'][word['correctAnswer']]
            random.shuffle(word['options'])
            word['correctAnswer'] = word['options'].index(correct_answer)
        
        return jsonify({
            'success': True,
            'words': quiz_words,
            'total_words': len(HSK1_WORDS),
            'new_words_count': len(quiz_words)
        })
        
    except Exception as e:
        return jsonify({
            'success': False,
            'message': f'Error retrieving next quiz: {str(e)}'
        }), 500