from flask import Blueprint, render_template, jsonify, request, session
import random

words_bp = Blueprint('words', __name__)

# HSK1 Words Database - 500 words
HSK1_WORDS = [
    
  { "id": 1, "word": "爱", "pinyin": "ài", "english": "love", "options": ["love", "hate", "like", "ignore"], "correctAnswer": 0 },
  { "id": 2, "word": "爱好", "pinyin": "ài hào", "english": "hobby", "options": ["hobby", "habit", "job", "study"], "correctAnswer": 0 },
  { "id": 3, "word": "八", "pinyin": "bā", "english": "eight", "options": ["seven", "eight", "six", "nine"], "correctAnswer": 1 },
  { "id": 4, "word": "爸爸", "pinyin": "bà ba", "english": "father", "options": ["mother", "uncle", "father", "brother"], "correctAnswer": 2 },
  { "id": 5, "word": "吧", "pinyin": "ba", "english": "suggestion particle", "options": ["statement", "command", "suggestion particle", "question"], "correctAnswer": 2 },
  { "id": 6, "word": "白", "pinyin": "bái", "english": "white", "options": ["black", "white", "red", "blue"], "correctAnswer": 1 },
  { "id": 7, "word": "白天", "pinyin": "bái tiān", "english": "daytime", "options": ["night", "daytime", "morning", "evening"], "correctAnswer": 1 },
  { "id": 8, "word": "百", "pinyin": "bǎi", "english": "hundred", "options": ["ten", "hundred", "thousand", "one"], "correctAnswer": 1 },
  { "id": 9, "word": "班", "pinyin": "bān", "english": "class", "options": ["class", "office", "home", "team"], "correctAnswer": 0 },
  { "id": 10, "word": "半", "pinyin": "bàn", "english": "half", "options": ["whole", "quarter", "half", "third"], "correctAnswer": 2 },
  { "id": 11, "word": "半年", "pinyin": "bàn nián", "english": "half a year", "options": ["one year", "half a year", "a month", "a week"], "correctAnswer": 1 },
  { "id": 12, "word": "半天", "pinyin": "bàn tiān", "english": "half a day", "options": ["whole day", "night", "half a day", "morning"], "correctAnswer": 2 },
  { "id": 13, "word": "帮", "pinyin": "bāng", "english": "help", "options": ["help", "play", "sleep", "eat"], "correctAnswer": 0 },
  { "id": 14, "word": "帮忙", "pinyin": "bāng máng", "english": "to help", "options": ["to sleep", "to help", "to wait", "to sing"], "correctAnswer": 1 },
  { "id": 15, "word": "包", "pinyin": "bāo", "english": "bag", "options": ["pen", "bag", "paper", "desk"], "correctAnswer": 1 },
  { "id": 16, "word": "包子", "pinyin": "bāo zi", "english": "bun", "options": ["rice", "noodle", "bun", "vegetable"], "correctAnswer": 2 },
  { "id": 17, "word": "杯", "pinyin": "bēi", "english": "cup (measure word)", "options": ["cup", "plate", "bowl", "glass"], "correctAnswer": 0 },
  { "id": 18, "word": "杯子", "pinyin": "bēi zi", "english": "cup", "options": ["cup", "fork", "plate", "knife"], "correctAnswer": 0 },
  { "id": 19, "word": "北", "pinyin": "běi", "english": "north", "options": ["south", "east", "north", "west"], "correctAnswer": 2 },
  { "id": 20, "word": "北边", "pinyin": "běi biān", "english": "north side", "options": ["east side", "north side", "west side", "south side"], "correctAnswer": 1 },
  { "id": 21, "word": "北京", "pinyin": "běi jīng", "english": "Beijing", "options": ["Shanghai", "Beijing", "Tokyo", "Seoul"], "correctAnswer": 1 },
  { "id": 22, "word": "本", "pinyin": "běn", "english": "book", "options": ["paper", "book", "pen", "chair"], "correctAnswer": 1 },
  { "id": 23, "word": "本子", "pinyin": "běn zi", "english": "notebook", "options": ["notebook", "ruler", "bag", "phone"], "correctAnswer": 0 },
  { "id": 24, "word": "比", "pinyin": "bǐ", "english": "compare", "options": ["compare", "write", "jump", "sing"], "correctAnswer": 0 },
  { "id": 25, "word": "别", "pinyin": "bié", "english": "don't", "options": ["do", "don't", "wait", "come"], "correctAnswer": 1 },
  { "id": 26, "word": "别的", "pinyin": "bié de", "english": "other", "options": ["other", "first", "last", "same"], "correctAnswer": 0 },
  { "id": 27, "word": "别人", "pinyin": "bié rén", "english": "other people", "options": ["himself", "other people", "family", "stranger"], "correctAnswer": 1 },
  { "id": 28, "word": "病", "pinyin": "bìng", "english": "illness", "options": ["health", "illness", "medicine", "doctor"], "correctAnswer": 1 },
  { "id": 29, "word": "病人", "pinyin": "bìng rén", "english": "patient", "options": ["doctor", "nurse", "patient", "teacher"], "correctAnswer": 2 },
  { "id": 30, "word": "不大", "pinyin": "bù dà", "english": "not big", "options": ["very big", "not big", "small", "old"], "correctAnswer": 1 },
  { "id": 31, "word": "不对", "pinyin": "bù duì", "english": "incorrect", "options": ["correct", "incorrect", "maybe", "right"], "correctAnswer": 1 },
  { "id": 32, "word": "不客气", "pinyin": "bú kè qi", "english": "you're welcome", "options": ["sorry", "please", "you're welcome", "goodbye"], "correctAnswer": 2 },
  { "id": 33, "word": "不用", "pinyin": "bú yòng", "english": "no need", "options": ["must", "no need", "hurry", "slow"], "correctAnswer": 1 },
  { "id": 34, "word": "不", "pinyin": "bù", "english": "not", "options": ["not", "yes", "why", "how"], "correctAnswer": 0 },
  { "id": 35, "word": "菜", "pinyin": "cài", "english": "dish/vegetable", "options": ["fruit", "dish", "drink", "bread"], "correctAnswer": 1 },
  { "id": 36, "word": "茶", "pinyin": "chá", "english": "tea", "options": ["milk", "tea", "juice", "water"], "correctAnswer": 1 },
  { "id": 37, "word": "差", "pinyin": "chà", "english": "bad", "options": ["good", "bad", "tired", "slow"], "correctAnswer": 1 },
  { "id": 38, "word": "常", "pinyin": "cháng", "english": "often", "options": ["never", "sometimes", "often", "rarely"], "correctAnswer": 2 },
  { "id": 39, "word": "常常", "pinyin": "cháng cháng", "english": "often", "options": ["always", "rarely", "never", "often"], "correctAnswer": 3 },
  { "id": 40, "word": "唱", "pinyin": "chàng", "english": "to sing", "options": ["to dance", "to sing", "to eat", "to write"], "correctAnswer": 1 },
  { "id": 41, "word": "唱歌", "pinyin": "chàng gē", "english": "to sing", "options": ["to draw", "to sing", "to listen", "to run"], "correctAnswer": 1 },
  { "id": 42, "word": "车", "pinyin": "chē", "english": "car", "options": ["train", "bike", "car", "bus"], "correctAnswer": 2 },
  { "id": 43, "word": "车票", "pinyin": "chē piào", "english": "ticket", "options": ["ticket", "card", "key", "coin"], "correctAnswer": 0 },
  { "id": 44, "word": "车上", "pinyin": "chē shàng", "english": "in the car", "options": ["on the car", "under the table", "in the car", "at home"], "correctAnswer": 2 },
  { "id": 45, "word": "车站", "pinyin": "chē zhàn", "english": "station", "options": ["station", "airport", "school", "store"], "correctAnswer": 0 },
  { "id": 46, "word": "吃", "pinyin": "chī", "english": "to eat", "options": ["to drink", "to sleep", "to eat", "to go"], "correctAnswer": 2 },
  { "id": 47, "word": "吃饭", "pinyin": "chī fàn", "english": "to have a meal", "options": ["to eat", "to sleep", "to run", "to read"], "correctAnswer": 0 },
  { "id": 48, "word": "出", "pinyin": "chū", "english": "to go out", "options": ["to enter", "to go out", "to sleep", "to fall"], "correctAnswer": 1 },
  { "id": 49, "word": "出来", "pinyin": "chū lái", "english": "come out", "options": ["go in", "come out", "sit", "sleep"], "correctAnswer": 1 },
  { "id": 50, "word": "出去", "pinyin": "chū qù", "english": "go out", "options": ["go out", "come in", "sit", "drive"], "correctAnswer": 0 },
  
  { "id": 51, "word": "次", "pinyin": "cì", "english": "time (occurrence)", "options": ["place", "time", "hour", "minute"], "correctAnswer": 1 },
  { "id": 52, "word": "从", "pinyin": "cóng", "english": "from", "options": ["to", "for", "from", "at"], "correctAnswer": 2 },
  { "id": 53, "word": "错", "pinyin": "cuò", "english": "wrong", "options": ["correct", "maybe", "wrong", "busy"], "correctAnswer": 2 },
  { "id": 54, "word": "打", "pinyin": "dǎ", "english": "to hit", "options": ["to hit", "to sleep", "to buy", "to fly"], "correctAnswer": 0 },
  { "id": 55, "word": "打车", "pinyin": "dǎ chē", "english": "take a taxi", "options": ["drive car", "take a taxi", "buy car", "wait at station"], "correctAnswer": 1 },
  { "id": 56, "word": "打电话", "pinyin": "dǎ diàn huà", "english": "make a phone call", "options": ["to sleep", "make a phone call", "to write", "to drive"], "correctAnswer": 1 },
  { "id": 57, "word": "打开", "pinyin": "dǎ kāi", "english": "to open", "options": ["to close", "to open", "to sell", "to cry"], "correctAnswer": 1 },
  { "id": 58, "word": "打球", "pinyin": "dǎ qiú", "english": "play ball", "options": ["play ball", "play guitar", "sleep", "cook"], "correctAnswer": 0 },
  { "id": 59, "word": "大", "pinyin": "dà", "english": "big", "options": ["small", "big", "slow", "far"], "correctAnswer": 1 },
  { "id": 60, "word": "大学", "pinyin": "dà xué", "english": "university", "options": ["high school", "university", "middle school", "primary school"], "correctAnswer": 1 },
  { "id": 61, "word": "大学生", "pinyin": "dà xué shēng", "english": "university student", "options": ["teacher", "university student", "driver", "doctor"], "correctAnswer": 1 },
  { "id": 62, "word": "到", "pinyin": "dào", "english": "to arrive", "options": ["leave", "to arrive", "to sleep", "to clean"], "correctAnswer": 1 },
  { "id": 63, "word": "得到", "pinyin": "dé dào", "english": "to get", "options": ["to lose", "to get", "to ask", "to cut"], "correctAnswer": 1 },
  { "id": 64, "word": "地", "pinyin": "de", "english": "(particle)", "options": ["very", "and", "(particle)", "only"], "correctAnswer": 2 },
  { "id": 65, "word": "得", "pinyin": "de", "english": "(structural particle)", "options": ["why", "and", "(structural particle)", "inside"], "correctAnswer": 2 },
  { "id": 66, "word": "等", "pinyin": "děng", "english": "to wait", "options": ["to wait", "to walk", "to eat", "to borrow"], "correctAnswer": 0 },
  { "id": 67, "word": "地方", "pinyin": "dì fang", "english": "place", "options": ["time", "money", "place", "home"], "correctAnswer": 2 },
  { "id": 68, "word": "弟弟", "pinyin": "dì di", "english": "younger brother", "options": ["older brother", "younger brother", "cousin", "friend"], "correctAnswer": 1 },
  { "id": 69, "word": "第一", "pinyin": "dì yī", "english": "first", "options": ["last", "first", "second", "third"], "correctAnswer": 1 },
  { "id": 70, "word": "点", "pinyin": "diǎn", "english": "o'clock", "options": ["minute", "hour", "o'clock", "second"], "correctAnswer": 2 },
  { "id": 71, "word": "电脑", "pinyin": "diàn nǎo", "english": "computer", "options": ["computer", "phone", "watch", "book"], "correctAnswer": 0 },
  { "id": 72, "word": "电视", "pinyin": "diàn shì", "english": "television", "options": ["radio", "television", "computer", "phone"], "correctAnswer": 1 },
  { "id": 73, "word": "电影", "pinyin": "diàn yǐng", "english": "movie", "options": ["song", "book", "movie", "game"], "correctAnswer": 2 },
  { "id": 74, "word": "东西", "pinyin": "dōng xi", "english": "thing", "options": ["person", "thing", "place", "animal"], "correctAnswer": 1 },
  { "id": 75, "word": "懂", "pinyin": "dǒng", "english": "to understand", "options": ["to teach", "to forget", "to understand", "to speak"], "correctAnswer": 2 },
  { "id": 76, "word": "都", "pinyin": "dōu", "english": "all", "options": ["all", "some", "few", "none"], "correctAnswer": 0 },
  { "id": 77, "word": "读", "pinyin": "dú", "english": "to read", "options": ["to write", "to read", "to sleep", "to cry"], "correctAnswer": 1 },
  { "id": 78, "word": "对", "pinyin": "duì", "english": "correct/right", "options": ["wrong", "right", "slow", "big"], "correctAnswer": 1 },
  { "id": 79, "word": "对不起", "pinyin": "duì bu qǐ", "english": "sorry", "options": ["sorry", "please", "goodbye", "thank you"], "correctAnswer": 0 },
  { "id": 80, "word": "多", "pinyin": "duō", "english": "many/much", "options": ["few", "slow", "many", "tall"], "correctAnswer": 2 },
  { "id": 81, "word": "多少", "pinyin": "duō shao", "english": "how many/how much", "options": ["why", "how many", "where", "when"], "correctAnswer": 1 },
  { "id": 82, "word": "饿", "pinyin": "è", "english": "hungry", "options": ["hungry", "full", "sad", "cold"], "correctAnswer": 0 },
  { "id": 83, "word": "儿子", "pinyin": "ér zi", "english": "son", "options": ["daughter", "father", "teacher", "son"], "correctAnswer": 3 },
  { "id": 84, "word": "二", "pinyin": "èr", "english": "two", "options": ["one", "three", "two", "five"], "correctAnswer": 2 },
  { "id": 85, "word": "饭", "pinyin": "fàn", "english": "meal/rice", "options": ["rice", "water", "tea", "fruit"], "correctAnswer": 0 },
  { "id": 86, "word": "饭店", "pinyin": "fàn diàn", "english": "restaurant", "options": ["school", "restaurant", "bank", "hospital"], "correctAnswer": 1 },
  { "id": 87, "word": "房间", "pinyin": "fáng jiān", "english": "room", "options": ["hall", "room", "kitchen", "bathroom"], "correctAnswer": 1 },
  { "id": 88, "word": "放", "pinyin": "fàng", "english": "to put", "options": ["to put", "to run", "to jump", "to fall"], "correctAnswer": 0 },
  { "id": 89, "word": "放假", "pinyin": "fàng jià", "english": "to take a vacation", "options": ["to study", "to take a vacation", "to work", "to wait"], "correctAnswer": 1 },
  { "id": 90, "word": "非常", "pinyin": "fēi cháng", "english": "very", "options": ["not", "very", "little", "far"], "correctAnswer": 1 },
  { "id": 91, "word": "飞机", "pinyin": "fēi jī", "english": "airplane", "options": ["airplane", "bus", "train", "ship"], "correctAnswer": 0 },
  { "id": 92, "word": "分钟", "pinyin": "fēn zhōng", "english": "minute", "options": ["hour", "minute", "second", "week"], "correctAnswer": 1 },
  { "id": 93, "word": "服务员", "pinyin": "fú wù yuán", "english": "waiter/waitress", "options": ["driver", "waiter", "doctor", "nurse"], "correctAnswer": 1 },
  { "id": 94, "word": "高", "pinyin": "gāo", "english": "tall/high", "options": ["short", "tall", "old", "slow"], "correctAnswer": 1 },
  { "id": 95, "word": "高兴", "pinyin": "gāo xìng", "english": "happy", "options": ["sad", "angry", "happy", "sick"], "correctAnswer": 2 },
  { "id": 96, "word": "告诉", "pinyin": "gào su", "english": "to tell", "options": ["to run", "to tell", "to sleep", "to eat"], "correctAnswer": 1 },
  { "id": 97, "word": "哥哥", "pinyin": "gē ge", "english": "older brother", "options": ["younger brother", "father", "older brother", "son"], "correctAnswer": 2 },
  { "id": 98, "word": "给", "pinyin": "gěi", "english": "to give", "options": ["take", "give", "buy", "sell"], "correctAnswer": 1 },
  { "id": 99, "word": "跟", "pinyin": "gēn", "english": "with/follow", "options": ["without", "with", "over", "before"], "correctAnswer": 1 },
  { "id": 100, "word": "工作", "pinyin": "gōng zuò", "english": "work", "options": ["work", "sleep", "eat", "play"], "correctAnswer": 0 },

  { "id": 101, "word": "狗", "pinyin": "gǒu", "english": "dog", "options": ["cat", "dog", "fish", "bird"], "correctAnswer": 1 },
  { "id": 102, "word": "故事", "pinyin": "gù shi", "english": "story", "options": ["news", "story", "song", "poem"], "correctAnswer": 1 },
  { "id": 103, "word": "关", "pinyin": "guān", "english": "to close", "options": ["to close", "to open", "to jump", "to buy"], "correctAnswer": 0 },
  { "id": 104, "word": "关门", "pinyin": "guān mén", "english": "close the door", "options": ["open door", "close door", "knock door", "fix door"], "correctAnswer": 1 },
  { "id": 105, "word": "关于", "pinyin": "guān yú", "english": "about", "options": ["before", "after", "about", "under"], "correctAnswer": 2 },
  { "id": 106, "word": "贵", "pinyin": "guì", "english": "expensive", "options": ["cheap", "hot", "expensive", "fast"], "correctAnswer": 2 },
  { "id": 107, "word": "国", "pinyin": "guó", "english": "country", "options": ["city", "village", "country", "town"], "correctAnswer": 2 },
  { "id": 108, "word": "国家", "pinyin": "guó jiā", "english": "country/nation", "options": ["city", "area", "country", "family"], "correctAnswer": 2 },
  { "id": 109, "word": "果汁", "pinyin": "guǒ zhī", "english": "fruit juice", "options": ["milk", "tea", "fruit juice", "water"], "correctAnswer": 2 },
  { "id": 110, "word": "过", "pinyin": "guò", "english": "to pass", "options": ["to pass", "to sit", "to cry", "to buy"], "correctAnswer": 0 },
  { "id": 111, "word": "还", "pinyin": "hái", "english": "still", "options": ["already", "still", "never", "late"], "correctAnswer": 1 },
  { "id": 112, "word": "还是", "pinyin": "hái shi", "english": "or (in a question)", "options": ["and", "or", "but", "if"], "correctAnswer": 1 },
  { "id": 113, "word": "孩子", "pinyin": "hái zi", "english": "child", "options": ["adult", "teacher", "child", "friend"], "correctAnswer": 2 },
  { "id": 114, "word": "汉语", "pinyin": "hàn yǔ", "english": "Chinese language", "options": ["English", "Chinese", "Korean", "Japanese"], "correctAnswer": 1 },
  { "id": 115, "word": "汉字", "pinyin": "hàn zì", "english": "Chinese character", "options": ["Chinese character", "number", "letter", "symbol"], "correctAnswer": 0 },
  { "id": 116, "word": "好", "pinyin": "hǎo", "english": "good", "options": ["bad", "cold", "good", "tired"], "correctAnswer": 2 },
  { "id": 117, "word": "好吃", "pinyin": "hǎo chī", "english": "delicious", "options": ["delicious", "bitter", "salty", "cold"], "correctAnswer": 0 },
  { "id": 118, "word": "好看", "pinyin": "hǎo kàn", "english": "good-looking", "options": ["beautiful", "good-looking", "ugly", "dirty"], "correctAnswer": 1 },
  { "id": 119, "word": "好听", "pinyin": "hǎo tīng", "english": "pleasant to hear", "options": ["loud", "pleasant to hear", "boring", "quiet"], "correctAnswer": 1 },
  { "id": 120, "word": "号", "pinyin": "hào", "english": "number", "options": ["name", "number", "day", "month"], "correctAnswer": 1 },
  { "id": 121, "word": "喝", "pinyin": "hē", "english": "to drink", "options": ["to eat", "to drink", "to buy", "to stand"], "correctAnswer": 1 },
  { "id": 122, "word": "和", "pinyin": "hé", "english": "and", "options": ["or", "but", "and", "from"], "correctAnswer": 2 },
  { "id": 123, "word": "很", "pinyin": "hěn", "english": "very", "options": ["not", "very", "little", "few"], "correctAnswer": 1 },
  { "id": 124, "word": "后面", "pinyin": "hòu miàn", "english": "behind", "options": ["front", "left", "right", "behind"], "correctAnswer": 3 },
  { "id": 125, "word": "花", "pinyin": "huā", "english": "flower/to spend", "options": ["flower", "tree", "grass", "stone"], "correctAnswer": 0 },
  { "id": 126, "word": "画", "pinyin": "huà", "english": "to draw/painting", "options": ["to write", "to draw", "to cook", "to run"], "correctAnswer": 1 },
  { "id": 127, "word": "坏", "pinyin": "huài", "english": "bad/broken", "options": ["good", "bad", "old", "slow"], "correctAnswer": 1 },
  { "id": 128, "word": "还", "pinyin": "huán", "english": "to return (something)", "options": ["to lend", "to return", "to take", "to leave"], "correctAnswer": 1 },
  { "id": 129, "word": "欢迎", "pinyin": "huān yíng", "english": "welcome", "options": ["sorry", "welcome", "goodbye", "please"], "correctAnswer": 1 },
  { "id": 130, "word": "换", "pinyin": "huàn", "english": "to change", "options": ["to change", "to eat", "to sit", "to read"], "correctAnswer": 0 },
  { "id": 131, "word": "黄", "pinyin": "huáng", "english": "yellow", "options": ["yellow", "blue", "red", "green"], "correctAnswer": 0 },
  { "id": 132, "word": "会", "pinyin": "huì", "english": "can/know how to", "options": ["must", "can", "maybe", "never"], "correctAnswer": 1 },
  { "id": 133, "word": "火车站", "pinyin": "huǒ chē zhàn", "english": "train station", "options": ["bus stop", "airport", "train station", "hotel"], "correctAnswer": 2 },
  { "id": 134, "word": "或是", "pinyin": "huò shì", "english": "or", "options": ["and", "but", "or", "so"], "correctAnswer": 2 },
  { "id": 135, "word": "机场", "pinyin": "jī chǎng", "english": "airport", "options": ["station", "airport", "school", "market"], "correctAnswer": 1 },
  { "id": 136, "word": "鸡蛋", "pinyin": "jī dàn", "english": "egg", "options": ["egg", "milk", "rice", "noodle"], "correctAnswer": 0 },
  { "id": 137, "word": "几", "pinyin": "jǐ", "english": "how many", "options": ["who", "how many", "where", "when"], "correctAnswer": 1 },
  { "id": 138, "word": "家", "pinyin": "jiā", "english": "home/family", "options": ["home", "school", "store", "farm"], "correctAnswer": 0 },
  { "id": 139, "word": "家人", "pinyin": "jiā rén", "english": "family members", "options": ["friends", "family members", "teachers", "students"], "correctAnswer": 1 },
  { "id": 140, "word": "间", "pinyin": "jiān", "english": "room (measure word)", "options": ["person", "room", "bottle", "chair"], "correctAnswer": 1 },
  { "id": 141, "word": "见", "pinyin": "jiàn", "english": "to see", "options": ["to see", "to hide", "to drink", "to fall"], "correctAnswer": 0 },
  { "id": 142, "word": "见面", "pinyin": "jiàn miàn", "english": "to meet", "options": ["to run", "to meet", "to call", "to cook"], "correctAnswer": 1 },
  { "id": 143, "word": "叫", "pinyin": "jiào", "english": "to be called", "options": ["to shout", "to be called", "to close", "to draw"], "correctAnswer": 1 },
  { "id": 144, "word": "教", "pinyin": "jiào", "english": "to teach", "options": ["to teach", "to learn", "to fly", "to eat"], "correctAnswer": 0 },
  { "id": 145, "word": "教师", "pinyin": "jiào shī", "english": "teacher", "options": ["teacher", "student", "doctor", "driver"], "correctAnswer": 0 },
  { "id": 146, "word": "姐姐", "pinyin": "jiě jie", "english": "older sister", "options": ["younger sister", "older sister", "mother", "friend"], "correctAnswer": 1 },
  { "id": 147, "word": "今天", "pinyin": "jīn tiān", "english": "today", "options": ["tomorrow", "yesterday", "today", "now"], "correctAnswer": 2 },
  { "id": 148, "word": "进", "pinyin": "jìn", "english": "to enter", "options": ["to enter", "to go out", "to open", "to cry"], "correctAnswer": 0 },
  { "id": 149, "word": "近", "pinyin": "jìn", "english": "near", "options": ["near", "far", "high", "slow"], "correctAnswer": 0 },
  { "id": 150, "word": "九", "pinyin": "jiǔ", "english": "nine", "options": ["eight", "nine", "seven", "ten"], "correctAnswer": 1 },
  
  { "id": 151, "word": "咖啡", "pinyin": "kā fēi", "english": "coffee", "options": ["tea", "milk", "coffee", "juice"], "correctAnswer": 2 },
  { "id": 152, "word": "开", "pinyin": "kāi", "english": "to open/to start", "options": ["to close", "to start", "to open", "to lose"], "correctAnswer": 2 },
  { "id": 153, "word": "开车", "pinyin": "kāi chē", "english": "to drive", "options": ["to fly", "to drive", "to sit", "to write"], "correctAnswer": 1 },
  { "id": 154, "word": "开心", "pinyin": "kāi xīn", "english": "happy", "options": ["sad", "happy", "angry", "tired"], "correctAnswer": 1 },
  { "id": 155, "word": "看", "pinyin": "kàn", "english": "to see/watch", "options": ["to hear", "to see", "to sleep", "to cook"], "correctAnswer": 1 },
  { "id": 156, "word": "看见", "pinyin": "kàn jiàn", "english": "to see", "options": ["to see", "to eat", "to close", "to shout"], "correctAnswer": 0 },
  { "id": 157, "word": "考试", "pinyin": "kǎo shì", "english": "exam", "options": ["class", "exam", "homework", "question"], "correctAnswer": 1 },
  { "id": 158, "word": "课", "pinyin": "kè", "english": "class/lesson", "options": ["lesson", "pen", "rest", "street"], "correctAnswer": 0 },
  { "id": 159, "word": "课本", "pinyin": "kè běn", "english": "textbook", "options": ["paper", "textbook", "ruler", "bag"], "correctAnswer": 1 },
  { "id": 160, "word": "块", "pinyin": "kuài", "english": "piece (measure word)/Yuan", "options": ["Yuan", "minute", "year", "kilogram"], "correctAnswer": 0 },
  { "id": 161, "word": "来", "pinyin": "lái", "english": "to come", "options": ["to go", "to come", "to sit", "to run"], "correctAnswer": 1 },
  { "id": 162, "word": "老师", "pinyin": "lǎo shī", "english": "teacher", "options": ["student", "doctor", "teacher", "friend"], "correctAnswer": 2 },
  { "id": 163, "word": "了", "pinyin": "le", "english": "(completed action particle)", "options": ["future", "(completed action)", "time", "not"], "correctAnswer": 1 },
  { "id": 164, "word": "累", "pinyin": "lèi", "english": "tired", "options": ["happy", "tired", "sad", "fast"], "correctAnswer": 1 },
  { "id": 165, "word": "冷", "pinyin": "lěng", "english": "cold", "options": ["hot", "cold", "tall", "wet"], "correctAnswer": 1 },
  { "id": 166, "word": "里", "pinyin": "lǐ", "english": "inside", "options": ["outside", "inside", "over", "under"], "correctAnswer": 1 },
  { "id": 167, "word": "六", "pinyin": "liù", "english": "six", "options": ["six", "seven", "eight", "ten"], "correctAnswer": 0 },
  { "id": 168, "word": "楼", "pinyin": "lóu", "english": "building", "options": ["forest", "building", "store", "kitchen"], "correctAnswer": 1 },
  { "id": 169, "word": "路", "pinyin": "lù", "english": "road", "options": ["school", "road", "bridge", "book"], "correctAnswer": 1 },
  { "id": 170, "word": "妈妈", "pinyin": "mā ma", "english": "mother", "options": ["father", "mother", "aunt", "sister"], "correctAnswer": 1 },
  { "id": 171, "word": "吗", "pinyin": "ma", "english": "question particle", "options": ["question particle", "statement", "negation", "command"], "correctAnswer": 0 },
  { "id": 172, "word": "买", "pinyin": "mǎi", "english": "to buy", "options": ["sell", "buy", "borrow", "eat"], "correctAnswer": 1 },
  { "id": 173, "word": "卖", "pinyin": "mài", "english": "to sell", "options": ["buy", "sell", "watch", "stand"], "correctAnswer": 1 },
  { "id": 174, "word": "慢", "pinyin": "màn", "english": "slow", "options": ["fast", "slow", "early", "late"], "correctAnswer": 1 },
  { "id": 175, "word": "忙", "pinyin": "máng", "english": "busy", "options": ["free", "busy", "tired", "cold"], "correctAnswer": 1 },
  { "id": 176, "word": "猫", "pinyin": "māo", "english": "cat", "options": ["dog", "cat", "fish", "horse"], "correctAnswer": 1 },
  { "id": 177, "word": "没有", "pinyin": "méi yǒu", "english": "don’t have", "options": ["have", "don’t have", "must", "wait"], "correctAnswer": 1 },
  { "id": 178, "word": "妹妹", "pinyin": "mèi mei", "english": "younger sister", "options": ["younger sister", "older sister", "aunt", "mother"], "correctAnswer": 0 },
  { "id": 179, "word": "门", "pinyin": "mén", "english": "door", "options": ["chair", "window", "door", "wall"], "correctAnswer": 2 },
  { "id": 180, "word": "门口", "pinyin": "mén kǒu", "english": "entrance", "options": ["exit", "entrance", "corner", "kitchen"], "correctAnswer": 1 },
  { "id": 181, "word": "米饭", "pinyin": "mǐ fàn", "english": "rice", "options": ["rice", "water", "tea", "noodle"], "correctAnswer": 0 },
  { "id": 182, "word": "名字", "pinyin": "míng zi", "english": "name", "options": ["age", "birthday", "name", "address"], "correctAnswer": 2 },
  { "id": 183, "word": "明天", "pinyin": "míng tiān", "english": "tomorrow", "options": ["today", "yesterday", "tomorrow", "now"], "correctAnswer": 2 },
  { "id": 184, "word": "奶奶", "pinyin": "nǎi nai", "english": "grandmother", "options": ["mother", "grandmother", "aunt", "sister"], "correctAnswer": 1 },
  { "id": 185, "word": "男", "pinyin": "nán", "english": "male", "options": ["female", "male", "child", "old"], "correctAnswer": 1 },
  { "id": 186, "word": "南", "pinyin": "nán", "english": "south", "options": ["north", "east", "south", "west"], "correctAnswer": 2 },
  { "id": 187, "word": "难", "pinyin": "nán", "english": "difficult", "options": ["easy", "difficult", "slow", "far"], "correctAnswer": 1 },
  { "id": 188, "word": "你", "pinyin": "nǐ", "english": "you", "options": ["I", "he", "you", "they"], "correctAnswer": 2 },
  { "id": 189, "word": "年", "pinyin": "nián", "english": "year", "options": ["day", "month", "year", "week"], "correctAnswer": 2 },
  { "id": 190, "word": "年轻", "pinyin": "nián qīng", "english": "young", "options": ["old", "young", "rich", "tall"], "correctAnswer": 1 },
  { "id": 191, "word": "鸟", "pinyin": "niǎo", "english": "bird", "options": ["dog", "bird", "cat", "fish"], "correctAnswer": 1 },
  { "id": 192, "word": "您", "pinyin": "nín", "english": "you (polite)", "options": ["you (polite)", "we", "she", "they"], "correctAnswer": 0 },
  { "id": 193, "word": "牛奶", "pinyin": "niú nǎi", "english": "milk", "options": ["tea", "milk", "water", "juice"], "correctAnswer": 1 },
  { "id": 194, "word": "女", "pinyin": "nǚ", "english": "female", "options": ["male", "female", "child", "father"], "correctAnswer": 1 },
  { "id": 195, "word": "旁边", "pinyin": "páng biān", "english": "beside", "options": ["in front", "behind", "beside", "above"], "correctAnswer": 2 },
  { "id": 196, "word": "朋友", "pinyin": "péng you", "english": "friend", "options": ["enemy", "friend", "teacher", "father"], "correctAnswer": 1 },
  { "id": 197, "word": "票", "pinyin": "piào", "english": "ticket", "options": ["ticket", "wallet", "key", "bag"], "correctAnswer": 0 },
  { "id": 198, "word": "苹果", "pinyin": "píng guǒ", "english": "apple", "options": ["banana", "grape", "apple", "orange"], "correctAnswer": 2 },
  { "id": 199, "word": "七", "pinyin": "qī", "english": "seven", "options": ["six", "seven", "nine", "ten"], "correctAnswer": 1 },
  { "id": 200, "word": "起床", "pinyin": "qǐ chuáng", "english": "to get up", "options": ["to sleep", "to eat", "to get up", "to sit"], "correctAnswer": 2 },
  
  { "id": 201, "word": "起来", "pinyin": "qǐ lái", "english": "stand up / get up", "options": ["to sit", "to sleep", "to get up", "to fall"], "correctAnswer": 2 },
  { "id": 202, "word": "汽车", "pinyin": "qì chē", "english": "car", "options": ["bike", "car", "train", "ship"], "correctAnswer": 1 },
  { "id": 203, "word": "前面", "pinyin": "qián miàn", "english": "in front", "options": ["behind", "beside", "in front", "under"], "correctAnswer": 2 },
  { "id": 204, "word": "钱", "pinyin": "qián", "english": "money", "options": ["water", "money", " rice", "clothes"], "correctAnswer": 1 },
  { "id": 205, "word": "请", "pinyin": "qǐng", "english": "please", "options": ["sorry", "please", "thank you", "no"], "correctAnswer": 1 },
  { "id": 206, "word": "请问", "pinyin": "qǐng wèn", "english": "may I ask", "options": ["may I ask", "hello", "goodbye", "never mind"], "correctAnswer": 0 },
  { "id": 207, "word": "秋", "pinyin": "qiū", "english": "autumn", "options": ["spring", "summer", "autumn", "winter"], "correctAnswer": 2 },
  { "id": 208, "word": "去", "pinyin": "qù", "english": "to go", "options": ["to come", "to go", "to stay", "to jump"], "correctAnswer": 1 },
  { "id": 209, "word": "去年", "pinyin": "qù nián", "english": "last year", "options": ["this year", "next year", "last year", "yesterday"], "correctAnswer": 2 },
  { "id": 210, "word": "热", "pinyin": "rè", "english": "hot", "options": ["cold", "hot", "wet", "slow"], "correctAnswer": 1 },
  { "id": 211, "word": "人", "pinyin": "rén", "english": "person", "options": ["person", "animal", "bird", "plant"], "correctAnswer": 0 },
  { "id": 212, "word": "认识", "pinyin": "rèn shi", "english": "to know / recognize", "options": ["to forget", "to recognize", "to run", "to hide"], "correctAnswer": 1 },
  { "id": 213, "word": "日", "pinyin": "rì", "english": "day", "options": ["month", "day", "year", "week"], "correctAnswer": 1 },
  { "id": 214, "word": "三", "pinyin": "sān", "english": "three", "options": ["two", "three", "four", "one"], "correctAnswer": 1 },
  { "id": 215, "word": "山", "pinyin": "shān", "english": "mountain", "options": ["river", "mountain", "tree", "house"], "correctAnswer": 1 },
  { "id": 216, "word": "商店", "pinyin": "shāng diàn", "english": "shop", "options": ["shop", "school", "kitchen", "station"], "correctAnswer": 0 },
  { "id": 217, "word": "上", "pinyin": "shàng", "english": "up/on", "options": ["under", "inside", "on", "behind"], "correctAnswer": 2 },
  { "id": 218, "word": "上午", "pinyin": "shàng wǔ", "english": "morning", "options": ["morning", "evening", "midnight", "afternoon"], "correctAnswer": 0 },
  { "id": 219, "word": "上课", "pinyin": "shàng kè", "english": "to attend class", "options": ["to sleep", "to eat", "to attend class", "to walk"], "correctAnswer": 2 },
  { "id": 220, "word": "上班", "pinyin": "shàng bān", "english": "to go to work", "options": ["to sleep", "to go to work", "to rest", "to jump"], "correctAnswer": 1 },
  { "id": 221, "word": "上午", "pinyin": "shàng wǔ", "english": "late morning", "options": ["evening", "afternoon", "morning", "midnight"], "correctAnswer": 2 },
  { "id": 222, "word": "少", "pinyin": "shǎo", "english": "few/less", "options": ["many", "few", "big", "fast"], "correctAnswer": 1 },
  { "id": 223, "word": "谁", "pinyin": "shéi", "english": "who", "options": ["what", "who", "when", "why"], "correctAnswer": 1 },
  { "id": 224, "word": "身体", "pinyin": "shēn tǐ", "english": "body/health", "options": ["body", "mind", "clothes", "food"], "correctAnswer": 0 },
  { "id": 225, "word": "什么", "pinyin": "shén me", "english": "what", "options": ["who", "why", "what", "how"], "correctAnswer": 2 },
  { "id": 226, "word": "生", "pinyin": "shēng", "english": "to be born", "options": ["to die", "to be born", "to eat", "to jump"], "correctAnswer": 1 },
  { "id": 227, "word": "生日", "pinyin": "shēng rì", "english": "birthday", "options": ["holiday", "birthday", "weekend", "festival"], "correctAnswer": 1 },
  { "id": 228, "word": "十", "pinyin": "shí", "english": "ten", "options": ["nine", "ten", "two", "five"], "correctAnswer": 1 },
  { "id": 229, "word": "时候", "pinyin": "shí hou", "english": "time/moment", "options": ["place", "time", "thing", "date"], "correctAnswer": 1 },
  { "id": 230, "word": "时间", "pinyin": "shí jiān", "english": "time", "options": ["time", "weather", "road", "snow"], "correctAnswer": 0 },
  { "id": 231, "word": "是", "pinyin": "shì", "english": "to be", "options": ["to be", "to have", "to go", "to think"], "correctAnswer": 0 },
  { "id": 232, "word": "手", "pinyin": "shǒu", "english": "hand", "options": ["hand", "head", "face", "leg"], "correctAnswer": 0 },
  { "id": 233, "word": "手机", "pinyin": "shǒu jī", "english": "mobile phone", "options": ["computer", "mobile phone", "book", "table"], "correctAnswer": 1 },
  { "id": 234, "word": "书", "pinyin": "shū", "english": "book", "options": ["book", "pen", "bag", "phone"], "correctAnswer": 0 },
  { "id": 235, "word": "书店", "pinyin": "shū diàn", "english": "bookstore", "options": ["library", "bookstore", "market", "park"], "correctAnswer": 1 },
  { "id": 236, "word": "树", "pinyin": "shù", "english": "tree", "options": ["flower", "tree", "grass", "stone"], "correctAnswer": 1 },
  { "id": 237, "word": "水", "pinyin": "shuǐ", "english": "water", "options": ["water", "milk", "tea", "wine"], "correctAnswer": 0 },
  { "id": 238, "word": "水果", "pinyin": "shuǐ guǒ", "english": "fruit", "options": ["rice", "fruit", "meat", "drink"], "correctAnswer": 1 },
  { "id": 239, "word": "睡", "pinyin": "shuì", "english": "to sleep", "options": ["to wake", "to sleep", "to wash", "to run"], "correctAnswer": 1 },
  { "id": 240, "word": "睡觉", "pinyin": "shuì jiào", "english": "to sleep", "options": ["to sleep", "to eat", "to read", "to go"], "correctAnswer": 0 },
  { "id": 241, "word": "说", "pinyin": "shuō", "english": "to speak", "options": ["to speak", "to fly", "to break", "to cook"], "correctAnswer": 0 },
  { "id": 242, "word": "四", "pinyin": "sì", "english": "four", "options": ["two", "five", "four", "three"], "correctAnswer": 2 },
  { "id": 243, "word": "送", "pinyin": "sòng", "english": "to send/to give", "options": ["to send", "to wash", "to cry", "to see"], "correctAnswer": 0 },
  { "id": 244, "word": "岁", "pinyin": "suì", "english": "year old", "options": ["year old", "month", "day", "time"], "correctAnswer": 0 },
  { "id": 245, "word": "他", "pinyin": "tā", "english": "he", "options": ["she", "they", "he", "you"], "correctAnswer": 2 },
  { "id": 246, "word": "她", "pinyin": "tā", "english": "she", "options": ["he", "they", "we", "she"], "correctAnswer": 3 },
  { "id": 247, "word": "它", "pinyin": "tā", "english": "it", "options": ["he", "she", "they", "it"], "correctAnswer": 3 },
  { "id": 248, "word": "太", "pinyin": "tài", "english": "too/very", "options": ["too", "few", "cold", "old"], "correctAnswer": 0 },
  { "id": 249, "word": "太阳", "pinyin": "tài yang", "english": "sun", "options": ["moon", "star", "sun", "cloud"], "correctAnswer": 2 },
  { "id": 250, "word": "天", "pinyin": "tiān", "english": "day/sky", "options": ["sky", "ocean", "road", "house"], "correctAnswer": 0 },

  { "id": 251, "word": "天气", "pinyin": "tiān qì", "english": "weather", "options": ["weather", "sky", "time", "season"], "correctAnswer": 0 },
  { "id": 252, "word": "听", "pinyin": "tīng", "english": "to listen", "options": ["to read", "to speak", "to listen", "to run"], "correctAnswer": 2 },
  { "id": 253, "word": "听见", "pinyin": "tīng jiàn", "english": "to hear", "options": ["to hear", "to see", "to sleep", "to write"], "correctAnswer": 0 },
  { "id": 254, "word": "同学", "pinyin": "tóng xué", "english": "classmate", "options": ["teacher", "classmate", "friend", "stranger"], "correctAnswer": 1 },
  { "id": 255, "word": "外", "pinyin": "wài", "english": "outside", "options": ["inside", "outside", "above", "behind"], "correctAnswer": 1 },
  { "id": 256, "word": "外国", "pinyin": "wài guó", "english": "foreign country", "options": ["city", "foreign country", "village", "home"], "correctAnswer": 1 },
  { "id": 257, "word": "晚上", "pinyin": "wǎn shang", "english": "evening", "options": ["morning", "evening", "afternoon", "noon"], "correctAnswer": 1 },
  { "id": 258, "word": "万", "pinyin": "wàn", "english": "ten thousand", "options": ["ten", "thousand", "ten thousand", "hundred"], "correctAnswer": 2 },
  { "id": 259, "word": "王", "pinyin": "wáng", "english": "surname Wang", "options": ["Wang", "Li", "Liu", "Zhang"], "correctAnswer": 0 },
  { "id": 260, "word": "忘", "pinyin": "wàng", "english": "to forget", "options": ["to remember", "to forget", "to write", "to buy"], "correctAnswer": 1 },
  { "id": 261, "word": "问", "pinyin": "wèn", "english": "to ask", "options": ["to ask", "to answer", "to sleep", "to run"], "correctAnswer": 0 },
  { "id": 262, "word": "我", "pinyin": "wǒ", "english": "I/me", "options": ["you", "he", "I", "they"], "correctAnswer": 2 },
  { "id": 263, "word": "我们", "pinyin": "wǒ men", "english": "we/us", "options": ["you", "they", "we", "he"], "correctAnswer": 2 },
  { "id": 264, "word": "五", "pinyin": "wǔ", "english": "five", "options": ["five", "four", "six", "seven"], "correctAnswer": 0 },
  { "id": 265, "word": "午饭", "pinyin": "wǔ fàn", "english": "lunch", "options": ["breakfast", "lunch", "coffee", "dinner"], "correctAnswer": 1 },
  { "id": 266, "word": "西", "pinyin": "xī", "english": "west", "options": ["north", "west", "south", "east"], "correctAnswer": 1 },
  { "id": 267, "word": "喜欢", "pinyin": "xǐ huan", "english": "to like", "options": ["to hate", "to like", "to cry", "to ask"], "correctAnswer": 1 },
  { "id": 268, "word": "洗", "pinyin": "xǐ", "english": "to wash", "options": ["to wash", "to eat", "to buy", "to wait"], "correctAnswer": 0 },
  { "id": 269, "word": "洗手间", "pinyin": "xǐ shǒu jiān", "english": "washroom/toilet", "options": ["classroom", "washroom", "kitchen", "bedroom"], "correctAnswer": 1 },
  { "id": 270, "word": "下午", "pinyin": "xià wǔ", "english": "afternoon", "options": ["morning", "night", "afternoon", "evening"], "correctAnswer": 2 },
  { "id": 271, "word": "下雨", "pinyin": "xià yǔ", "english": "to rain", "options": ["to snow", "to sleep", "to rain", "to sit"], "correctAnswer": 2 },
  { "id": 272, "word": "先生", "pinyin": "xiān sheng", "english": "Mr./sir", "options": ["teacher", "sir", "friend", "uncle"], "correctAnswer": 1 },
  { "id": 273, "word": "现在", "pinyin": "xiàn zài", "english": "now", "options": ["later", "tomorrow", "now", "yesterday"], "correctAnswer": 2 },
  { "id": 274, "word": "想", "pinyin": "xiǎng", "english": "to want/to think", "options": ["to think", "to forget", "to sit", "to walk"], "correctAnswer": 0 },
  { "id": 275, "word": "小", "pinyin": "xiǎo", "english": "small", "options": ["big", "small", "tall", "short"], "correctAnswer": 1 },
  { "id": 276, "word": "小姐", "pinyin": "xiǎo jie", "english": "Miss", "options": ["Sir", "Miss", "Mister", "Doctor"], "correctAnswer": 1 },
  { "id": 277, "word": "小时", "pinyin": "xiǎo shí", "english": "hour", "options": ["minute", "week", "day", "hour"], "correctAnswer": 3 },
  { "id": 278, "word": "笑", "pinyin": "xiào", "english": "to smile/laugh", "options": ["to cry", "to smile", "to hit", "to cook"], "correctAnswer": 1 },
  { "id": 279, "word": "写", "pinyin": "xiě", "english": "to write", "options": ["to write", "to read", "to wash", "to sing"], "correctAnswer": 0 },
  { "id": 280, "word": "谢谢", "pinyin": "xiè xie", "english": "thank you", "options": ["sorry", "please", "thank you", "hello"], "correctAnswer": 2 },
  { "id": 281, "word": "新", "pinyin": "xīn", "english": "new", "options": ["old", "new", "slow", "cheap"], "correctAnswer": 1 },
  { "id": 282, "word": "星期", "pinyin": "xīng qī", "english": "week", "options": ["year", "week", "month", "day"], "correctAnswer": 1 },
  { "id": 283, "word": "星期天", "pinyin": "xīng qī tiān", "english": "Sunday", "options": ["Monday", "Sunday", "Tuesday", "Friday"], "correctAnswer": 1 },
  { "id": 284, "word": "行", "pinyin": "xíng", "english": "OK/to go", "options": ["no", "OK", "wait", "stop"], "correctAnswer": 1 },
  { "id": 285, "word": "姓", "pinyin": "xìng", "english": "surname", "options": ["name", "surname", "nickname", "title"], "correctAnswer": 1 },
  { "id": 286, "word": "兄弟", "pinyin": "xiōng dì", "english": "brothers", "options": ["parents", "brothers", "friends", "sisters"], "correctAnswer": 1 },
  { "id": 287, "word": "休息", "pinyin": "xiū xi", "english": "to rest", "options": ["to work", "to run", "to rest", "to read"], "correctAnswer": 2 },
  { "id": 288, "word": "学", "pinyin": "xué", "english": "to study", "options": ["to teach", "to study", "to forget", "to ask"], "correctAnswer": 1 },
  { "id": 289, "word": "学生", "pinyin": "xué sheng", "english": "student", "options": ["student", "teacher", "driver", "doctor"], "correctAnswer": 0 },
  { "id": 290, "word": "学校", "pinyin": "xué xiào", "english": "school", "options": ["hospital", "school", "park", "bank"], "correctAnswer": 1 },
  { "id": 291, "word": "学习", "pinyin": "xué xí", "english": "to study", "options": ["to speak", "to study", "to forget", "to sleep"], "correctAnswer": 1 },
  { "id": 292, "word": "鸭", "pinyin": "yā", "english": "duck", "options": ["duck", "chicken", "fish", "cow"], "correctAnswer": 0 },
  { "id": 293, "word": "呀", "pinyin": "ya", "english": "exclamation particle", "options": ["question", "exclamation particle", "negation", "number"], "correctAnswer": 1 },
  { "id": 294, "word": "眼睛", "pinyin": "yǎn jing", "english": "eyes", "options": ["ears", "eyes", "mouth", "nose"], "correctAnswer": 1 },
  { "id": 295, "word": "羊肉", "pinyin": "yáng ròu", "english": "mutton", "options": ["beef", "chicken", "mutton", "pork"], "correctAnswer": 2 },
  { "id": 296, "word": "要", "pinyin": "yào", "english": "to want", "options": ["to run", "to want", "to sleep", "to wait"], "correctAnswer": 1 },
  { "id": 297, "word": "药", "pinyin": "yào", "english": "medicine", "options": ["water", "medicine", "food", "drink"], "correctAnswer": 1 },
  { "id": 298, "word": "也", "pinyin": "yě", "english": "also/too", "options": ["not", "already", "too", "still"], "correctAnswer": 2 },
  { "id": 299, "word": "一", "pinyin": "yī", "english": "one", "options": ["two", "five", "one", "three"], "correctAnswer": 2 },
  { "id": 300, "word": "一样", "pinyin": "yí yàng", "english": "same", "options": ["different", "same", "empty", "full"], "correctAnswer": 1 },
  
  { "id": 301, "word": "一点儿", "pinyin": "yì diǎnr", "english": "a little", "options": ["a lot", "a little", "none", "all"], "correctAnswer": 1 },
  { "id": 302, "word": "一起", "pinyin": "yì qǐ", "english": "together", "options": ["alone", "together", "after", "before"], "correctAnswer": 1 },
  { "id": 303, "word": "一样", "pinyin": "yí yàng", "english": "same", "options": ["different", "same", "old", "new"], "correctAnswer": 1 },
  { "id": 304, "word": "医生", "pinyin": "yī shēng", "english": "doctor", "options": ["nurse", "teacher", "doctor", "farmer"], "correctAnswer": 2 },
  { "id": 305, "word": "医院", "pinyin": "yī yuàn", "english": "hospital", "options": ["school", "hospital", "bank", "park"], "correctAnswer": 1 },
  { "id": 306, "word": "衣服", "pinyin": "yī fu", "english": "clothes", "options": ["clothes", "food", "book", "water"], "correctAnswer": 0 },
  { "id": 307, "word": "椅子", "pinyin": "yǐ zi", "english": "chair", "options": ["table", "chair", "door", "window"], "correctAnswer": 1 },
  { "id": 308, "word": "以后", "pinyin": "yǐ hòu", "english": "after", "options": ["before", "after", "now", "soon"], "correctAnswer": 1 },
  { "id": 309, "word": "以前", "pinyin": "yǐ qián", "english": "before", "options": ["later", "before", "now", "after"], "correctAnswer": 1 },
  { "id": 310, "word": "阴", "pinyin": "yīn", "english": "cloudy", "options": ["sunny", "cloudy", "wet", "snowy"], "correctAnswer": 1 },
  { "id": 311, "word": "因为", "pinyin": "yīn wèi", "english": "because", "options": ["because", "however", "so", "but"], "correctAnswer": 0 },
  { "id": 312, "word": "银行", "pinyin": "yín háng", "english": "bank", "options": ["bank", "school", "hotel", "shop"], "correctAnswer": 0 },
  { "id": 313, "word": "应该", "pinyin": "yīng gāi", "english": "should", "options": ["can", "should", "mustn't", "may"], "correctAnswer": 1 },
  { "id": 314, "word": "游泳", "pinyin": "yóu yǒng", "english": "to swim", "options": ["to read", "to swim", "to drive", "to write"], "correctAnswer": 1 },
  { "id": 315, "word": "右边", "pinyin": "yòu bian", "english": "right side", "options": ["left", "right", "front", "back"], "correctAnswer": 1 },
  { "id": 316, "word": "有", "pinyin": "yǒu", "english": "to have", "options": ["to have", "to be", "to do", "to go"], "correctAnswer": 0 },
  { "id": 317, "word": "有名", "pinyin": "yǒu míng", "english": "famous", "options": ["poor", "fast", "famous", "slow"], "correctAnswer": 2 },
  { "id": 318, "word": "雨", "pinyin": "yǔ", "english": "rain", "options": ["wind", "snow", "rain", "cloud"], "correctAnswer": 2 },
  { "id": 319, "word": "鱼", "pinyin": "yú", "english": "fish", "options": ["pork", "rice", "fish", "water"], "correctAnswer": 2 },
  { "id": 320, "word": "元", "pinyin": "yuán", "english": "yuan (currency)", "options": ["dollar", "yen", "yuan", "pound"], "correctAnswer": 2 },
  { "id": 321, "word": "远", "pinyin": "yuǎn", "english": "far", "options": ["near", "far", "slow", "fast"], "correctAnswer": 1 },
  { "id": 322, "word": "运动", "pinyin": "yùn dòng", "english": "sports/exercise", "options": ["painting", "sports", "talking", "watching"], "correctAnswer": 1 },
  { "id": 323, "word": "再", "pinyin": "zài", "english": "again", "options": ["never", "always", "again", "first"], "correctAnswer": 2 },
  { "id": 324, "word": "再见", "pinyin": "zài jiàn", "english": "goodbye", "options": ["hello", "goodbye", "please", "sorry"], "correctAnswer": 1 },
  { "id": 325, "word": "早", "pinyin": "zǎo", "english": "early", "options": ["early", "late", "tomorrow", "today"], "correctAnswer": 0 },
  { "id": 326, "word": "早上", "pinyin": "zǎo shang", "english": "morning", "options": ["evening", "morning", "night", "noon"], "correctAnswer": 1 },
  { "id": 327, "word": "怎么", "pinyin": "zěn me", "english": "how", "options": ["what", "why", "how", "when"], "correctAnswer": 2 },
  { "id": 328, "word": "怎么样", "pinyin": "zěn me yàng", "english": "how about", "options": ["how about", "why", "when", "where"], "correctAnswer": 0 },
  { "id": 329, "word": "站", "pinyin": "zhàn", "english": "to stand", "options": ["to sit", "to lie", "to stand", "to walk"], "correctAnswer": 2 },
  { "id": 330, "word": "找", "pinyin": "zhǎo", "english": "to look for", "options": ["to find", "to ask", "to look for", "to forget"], "correctAnswer": 2 },
  { "id": 331, "word": "着", "pinyin": "zhe", "english": "continuous action marker", "options": ["past", "future", "continuous", "question"], "correctAnswer": 2 },
  { "id": 332, "word": "真", "pinyin": "zhēn", "english": "real/really", "options": ["fake", "real", "cold", "tall"], "correctAnswer": 1 },
  { "id": 333, "word": "知道", "pinyin": "zhī dao", "english": "to know", "options": ["to forget", "to know", "to jump", "to rest"], "correctAnswer": 1 },
  { "id": 334, "word": "中间", "pinyin": "zhōng jiān", "english": "middle", "options": ["top", "bottom", "middle", "side"], "correctAnswer": 2 },
  { "id": 335, "word": "中国", "pinyin": "Zhōng guó", "english": "China", "options": ["Japan", "China", "Korea", "India"], "correctAnswer": 1 },
  { "id": 336, "word": "中文", "pinyin": "Zhōng wén", "english": "Chinese language", "options": ["English", "Japanese", "Chinese", "French"], "correctAnswer": 2 },
  { "id": 337, "word": "中午", "pinyin": "zhōng wǔ", "english": "noon", "options": ["morning", "noon", "evening", "night"], "correctAnswer": 1 },
  { "id": 338, "word": "住", "pinyin": "zhù", "english": "to live", "options": ["to die", "to live", "to cry", "to sleep"], "correctAnswer": 1 },
  { "id": 339, "word": "桌子", "pinyin": "zhuō zi", "english": "table", "options": ["chair", "sofa", "table", "bed"], "correctAnswer": 2 },
  { "id": 340, "word": "字", "pinyin": "zì", "english": "character", "options": ["character", "color", "sound", "food"], "correctAnswer": 0 },
  { "id": 341, "word": "自己", "pinyin": "zì jǐ", "english": "self", "options": ["self", "other", "friend", "enemy"], "correctAnswer": 0 },
  { "id": 342, "word": "走", "pinyin": "zǒu", "english": "to walk", "options": ["to run", "to walk", "to eat", "to sleep"], "correctAnswer": 1 },
  { "id": 343, "word": "最", "pinyin": "zuì", "english": "most", "options": ["least", "most", "slow", "short"], "correctAnswer": 1 },
  { "id": 344, "word": "昨", "pinyin": "zuó", "english": "yesterday", "options": ["tomorrow", "today", "yesterday", "now"], "correctAnswer": 2 },
  { "id": 345, "word": "昨天", "pinyin": "zuó tiān", "english": "yesterday", "options": ["yesterday", "tomorrow", "today", "now"], "correctAnswer": 0 },
  { "id": 346, "word": "左边", "pinyin": "zuǒ bia", "english": "left side", "options": ["right", "left", "behind", "front"], "correctAnswer": 1 },
  { "id": 347, "word": "做", "pinyin": "zuò", "english": "to do/make", "options": ["to do", "to sit", "to sleep", "to wait"], "correctAnswer": 0 },
  { "id": 348, "word": "坐", "pinyin": "zuò", "english": "to sit", "options": ["to stand", "to run", "to sit", "to eat"], "correctAnswer": 2 },
  { "id": 349, "word": "昨天晚上", "pinyin": "zuó tiān wǎn shang", "english": "last night", "options": ["tomorrow night", "last night", "this morning", "today noon"], "correctAnswer": 1 },
  { "id": 350, "word": "中文老师", "pinyin": "Zhōng wén lǎo shī", "english": "Chinese teacher", "options": ["math teacher", "Chinese teacher", "doctor", "driver"], "correctAnswer": 1 },
  
  { "id": 351, "word": "杯子", "pinyin": "bēi zi", "english": "cup", "options": ["plate", "cup", "bottle", "bowl"], "correctAnswer": 1 },
  { "id": 352, "word": "北边", "pinyin": "běi bian", "english": "north side", "options": ["south side", "east side", "north side", "west side"], "correctAnswer": 2 },
  { "id": 353, "word": "鼻子", "pinyin": "bí zi", "english": "nose", "options": ["ear", "eye", "nose", "mouth"], "correctAnswer": 2 },
  { "id": 354, "word": "别", "pinyin": "bié", "english": "don't", "options": ["yes", "don't", "can", "again"], "correctAnswer": 1 },
  { "id": 355, "word": "冰", "pinyin": "bīng", "english": "ice", "options": ["fire", "ice", "water", "snow"], "correctAnswer": 1 },
  { "id": 356, "word": "饼干", "pinyin": "bǐng gān", "english": "biscuit/cookie", "options": ["biscuit", "rice", "noodle", "milk"], "correctAnswer": 0 },
  { "id": 357, "word": "不客气", "pinyin": "bú kè qi", "english": "you're welcome", "options": ["please", "sorry", "you're welcome", "goodbye"], "correctAnswer": 2 },
  { "id": 358, "word": "菜单", "pinyin": "cài dān", "english": "menu", "options": ["recipe", "menu", "bill", "note"], "correctAnswer": 1 },
  { "id": 359, "word": "唱歌", "pinyin": "chàng gē", "english": "to sing", "options": ["to dance", "to sing", "to speak", "to cry"], "correctAnswer": 1 },
  { "id": 360, "word": "超市", "pinyin": "chāo shì", "english": "supermarket", "options": ["hospital", "supermarket", "park", "bank"], "correctAnswer": 1 },
  { "id": 361, "word": "衬衫", "pinyin": "chèn shān", "english": "shirt", "options": ["pants", "shirt", "coat", "hat"], "correctAnswer": 1 },
  { "id": 362, "word": "城市", "pinyin": "chéng shì", "english": "city", "options": ["village", "city", "road", "station"], "correctAnswer": 1 },
  { "id": 363, "word": "迟到", "pinyin": "chí dào", "english": "to be late", "options": ["to wait", "to be late", "to come", "to forget"], "correctAnswer": 1 },
  { "id": 364, "word": "打电话", "pinyin": "dǎ diàn huà", "english": "to make a call", "options": ["to write", "to make a call", "to eat", "to wash"], "correctAnswer": 1 },
  { "id": 365, "word": "打扫", "pinyin": "dǎ sǎo", "english": "to clean", "options": ["to run", "to clean", "to sing", "to ask"], "correctAnswer": 1 },
  { "id": 366, "word": "打算", "pinyin": "dǎ suàn", "english": "to plan", "options": ["to plan", "to cry", "to walk", "to rest"], "correctAnswer": 0 },
  { "id": 367, "word": "带", "pinyin": "dài", "english": "to bring", "options": ["to buy", "to bring", "to sell", "to shout"], "correctAnswer": 1 },
  { "id": 368, "word": "蛋糕", "pinyin": "dàn gāo", "english": "cake", "options": ["cake", "rice", "meat", "soup"], "correctAnswer": 0 },
  { "id": 369, "word": "但是", "pinyin": "dàn shì", "english": "but", "options": ["and", "but", "so", "then"], "correctAnswer": 1 },
  { "id": 370, "word": "地方", "pinyin": "dì fang", "english": "place", "options": ["place", "time", "food", "drink"], "correctAnswer": 0 },
  { "id": 371, "word": "地铁", "pinyin": "dì tiě", "english": "subway", "options": ["subway", "car", "bus", "train"], "correctAnswer": 0 },
  { "id": 372, "word": "地图", "pinyin": "dì tú", "english": "map", "options": ["book", "map", "pen", "bag"], "correctAnswer": 1 },
  { "id": 373, "word": "电梯", "pinyin": "diàn tī", "english": "elevator", "options": ["stairs", "elevator", "door", "kitchen"], "correctAnswer": 1 },
  { "id": 374, "word": "电子邮件", "pinyin": "diàn zǐ yóu jiàn", "english": "email", "options": ["message", "email", "letter", "call"], "correctAnswer": 1 },
  { "id": 375, "word": "东西", "pinyin": "dōng xi", "english": "thing", "options": ["food", "thing", "animal", "place"], "correctAnswer": 1 },
  { "id": 376, "word": "动物", "pinyin": "dòng wù", "english": "animal", "options": ["animal", "fruit", "place", "food"], "correctAnswer": 0 },
  { "id": 377, "word": "短", "pinyin": "duǎn", "english": "short", "options": ["long", "short", "tall", "heavy"], "correctAnswer": 1 },
  { "id": 378, "word": "段", "pinyin": "duàn", "english": "section", "options": ["line", "section", "page", "end"], "correctAnswer": 1 },
  { "id": 379, "word": "多", "pinyin": "duō", "english": "many/much", "options": ["few", "many", "tall", "hot"], "correctAnswer": 1 },
  { "id": 380, "word": "多么", "pinyin": "duō me", "english": "how (exclamatory)", "options": ["why", "how", "who", "when"], "correctAnswer": 1 },
  { "id": 381, "word": "饿", "pinyin": "è", "english": "hungry", "options": ["hungry", "thirsty", "sleepy", "angry"], "correctAnswer": 0 },
  { "id": 382, "word": "儿子", "pinyin": "ér zi", "english": "son", "options": ["daughter", "son", "father", "friend"], "correctAnswer": 1 },
  { "id": 383, "word": "发", "pinyin": "fā", "english": "to send", "options": ["to send", "to eat", "to play", "to wait"], "correctAnswer": 0 },
  { "id": 384, "word": "发烧", "pinyin": "fā shāo", "english": "to have a fever", "options": ["to have a fever", "to sleep", "to run", "to fall"], "correctAnswer": 0 },
  { "id": 385, "word": "放心", "pinyin": "fàng xīn", "english": "to rest assured", "options": ["to worry", "to rest assured", "to doubt", "to cry"], "correctAnswer": 1 },
  { "id": 386, "word": "方便", "pinyin": "fāng biàn", "english": "convenient", "options": ["slow", "convenient", "old", "cold"], "correctAnswer": 1 },
  { "id": 387, "word": "放", "pinyin": "fàng", "english": "to put", "options": ["to stop", "to put", "to drink", "to open"], "correctAnswer": 1 },
  { "id": 388, "word": "飞机", "pinyin": "fēi jī", "english": "airplane", "options": ["train", "bus", "airplane", "boat"], "correctAnswer": 2 },
  { "id": 389, "word": "分", "pinyin": "fēn", "english": "minute", "options": ["hour", "minute", "day", "second"], "correctAnswer": 1 },
  { "id": 390, "word": "服务员", "pinyin": "fú wù yuán", "english": "waiter/waitress", "options": ["waiter", "driver", "doctor", "teacher"], "correctAnswer": 0 },
  { "id": 391, "word": "附近", "pinyin": "fù jìn", "english": "nearby", "options": ["far", "nearby", "slow", "high"], "correctAnswer": 1 },
  { "id": 392, "word": "复习", "pinyin": "fù xí", "english": "to review", "options": ["to teach", "to review", "to listen", "to forget"], "correctAnswer": 1 },
  { "id": 393, "word": "干净", "pinyin": "gān jìng", "english": "clean", "options": ["dirty", "clean", "slow", "fat"], "correctAnswer": 1 },
  { "id": 394, "word": "感冒", "pinyin": "gǎn mào", "english": "cold/flu", "options": ["flu", "injury", "food", "sleep"], "correctAnswer": 0 },
  { "id": 395, "word": "高", "pinyin": "gāo", "english": "tall/high", "options": ["tall", "short", "slow", "poor"], "correctAnswer": 0 },
  { "id": 396, "word": "告诉", "pinyin": "gào su", "english": "to tell", "options": ["to tell", "to eat", "to hear", "to cook"], "correctAnswer": 0 },
  { "id": 397, "word": "哥哥", "pinyin": "gē ge", "english": "older brother", "options": ["younger brother", "older brother", "father", "uncle"], "correctAnswer": 1 },
  { "id": 398, "word": "给", "pinyin": "gěi", "english": "to give", "options": ["to take", "to give", "to wait", "to read"], "correctAnswer": 1 },
  { "id": 399, "word": "跟", "pinyin": "gēn", "english": "with/follow", "options": ["with", "without", "after", "before"], "correctAnswer": 0 },
  { "id": 400, "word": "更", "pinyin": "gèng", "english": "even more", "options": ["less", "even more", "slow", "late"], "correctAnswer": 1 },
  
  { "id": 401, "word": "工作", "pinyin": "gōng zuò", "english": "work/job", "options": ["rest", "work", "food", "sleep"], "correctAnswer": 1 },
  { "id": 402, "word": "公园", "pinyin": "gōng yuán", "english": "park", "options": ["hospital", "park", "school", "bank"], "correctAnswer": 1 },
  { "id": 403, "word": "故事", "pinyin": "gù shi", "english": "story", "options": ["poem", "story", "news", "song"], "correctAnswer": 1 },
  { "id": 404, "word": "刮风", "pinyin": "guā fēng", "english": "windy", "options": ["rainy", "windy", "sunny", "snowy"], "correctAnswer": 1 },
  { "id": 405, "word": "关", "pinyin": "guān", "english": "to close", "options": ["to open", "to close", "to buy", "to cry"], "correctAnswer": 1 },
  { "id": 406, "word": "关系", "pinyin": "guān xi", "english": "relationship", "options": ["place", "relationship", "food", "hobby"], "correctAnswer": 1 },
  { "id": 407, "word": "关于", "pinyin": "guān yú", "english": "about/concerning", "options": ["before", "about", "after", "without"], "correctAnswer": 1 },
  { "id": 408, "word": "贵", "pinyin": "guì", "english": "expensive", "options": ["cheap", "expensive", "ugly", "slow"], "correctAnswer": 1 },
  { "id": 409, "word": "国外", "pinyin": "guó wài", "english": "abroad", "options": ["home", "abroad", "village", "school"], "correctAnswer": 1 },
  { "id": 410, "word": "国家", "pinyin": "guó jiā", "english": "country", "options": ["city", "country", "bridge", "island"], "correctAnswer": 1 },
  { "id": 411, "word": "过", "pinyin": "guò", "english": "to pass/experience", "options": ["to pass", "to run", "to eat", "to lie"], "correctAnswer": 0 },
  { "id": 412, "word": "还是", "pinyin": "hái shi", "english": "or/still", "options": ["and", "or", "but", "so"], "correctAnswer": 1 },
  { "id": 413, "word": "还有", "pinyin": "hái yǒu", "english": "still have", "options": ["still have", "don't know", "finish", "leave"], "correctAnswer": 0 },
  { "id": 414, "word": "害怕", "pinyin": "hài pà", "english": "to be afraid", "options": ["to love", "to be afraid", "to know", "to jump"], "correctAnswer": 1 },
  { "id": 415, "word": "汉语", "pinyin": "hàn yǔ", "english": "Chinese language", "options": ["English", "Chinese", "Korean", "Japanese"], "correctAnswer": 1 },
  { "id": 416, "word": "河", "pinyin": "hé", "english": "river", "options": ["lake", "river", "tree", "mountain"], "correctAnswer": 1 },
  { "id": 417, "word": "黑板", "pinyin": "hēi bǎn", "english": "blackboard", "options": ["window", "blackboard", "desk", "cup"], "correctAnswer": 1 },
  { "id": 418, "word": "护照", "pinyin": "hù zhào", "english": "passport", "options": ["ID card", "passport", "ticket", "bill"], "correctAnswer": 1 },
  { "id": 419, "word": "花", "pinyin": "huā", "english": "flower", "options": ["tree", "flower", "grass", "mountain"], "correctAnswer": 1 },
  { "id": 420, "word": "画", "pinyin": "huà", "english": "to draw/painting", "options": ["to draw", "to eat", "to fly", "to drink"], "correctAnswer": 0 },
  { "id": 421, "word": "坏", "pinyin": "huài", "english": "bad/broken", "options": ["good", "bad", "new", "light"], "correctAnswer": 1 },
  { "id": 422, "word": "欢迎", "pinyin": "huān yíng", "english": "welcome", "options": ["goodbye", "welcome", "sorry", "please"], "correctAnswer": 1 },
  { "id": 423, "word": "还", "pinyin": "huán", "english": "to return", "options": ["to return", "to sleep", "to sell", "to wait"], "correctAnswer": 0 },
  { "id": 424, "word": "环境", "pinyin": "huán jìng", "english": "environment", "options": ["nature", "climate", "environment", "space"], "correctAnswer": 2 },
  { "id": 425, "word": "换", "pinyin": "huàn", "english": "to change/exchange", "options": ["to cry", "to dance", "to change", "to clean"], "correctAnswer": 2 },
  { "id": 426, "word": "黄", "pinyin": "huáng", "english": "yellow", "options": ["yellow", "blue", "green", "red"], "correctAnswer": 0 },
  { "id": 427, "word": "会议", "pinyin": "huì yì", "english": "meeting", "options": ["party", "meeting", "coffee", "shop"], "correctAnswer": 1 },
  { "id": 428, "word": "火车站", "pinyin": "huǒ chē zhàn", "english": "train station", "options": ["bus stop", "train station", "airport", "school"], "correctAnswer": 1 },
  { "id": 429, "word": "或者", "pinyin": "huò zhě", "english": "or", "options": ["and", "or", "but", "so"], "correctAnswer": 1 },
  { "id": 430, "word": "飞机票", "pinyin": "fēi jī piào", "english": "plane ticket", "options": ["train ticket", "plane ticket", "taxi", "passport"], "correctAnswer": 1 },
  { "id": 431, "word": "机场", "pinyin": "jī chǎng", "english": "airport", "options": ["train station", "airport", "hotel", "park"], "correctAnswer": 1 },
  { "id": 432, "word": "记得", "pinyin": "jì de", "english": "to remember", "options": ["to remember", "to forget", "to smile", "to sleep"], "correctAnswer": 0 },
  { "id": 433, "word": "季节", "pinyin": "jì jié", "english": "season", "options": ["year", "season", "month", "week"], "correctAnswer": 1 },
  { "id": 434, "word": "服务", "pinyin": "fú wù", "english": "service", "options": ["service", "waiter", "ticket", "shop"], "correctAnswer": 0 },
  { "id": 435, "word": "机会", "pinyin": "jī huì", "english": "opportunity", "options": ["chance", "time", "mistake", "idea"], "correctAnswer": 0 },
  { "id": 436, "word": "鸡蛋", "pinyin": "jī dàn", "english": "egg", "options": ["rice", "egg", "meat", "milk"], "correctAnswer": 1 },
  { "id": 437, "word": "极", "pinyin": "jí", "english": "extremely", "options": ["lightly", "extremely", "rarely", "slowly"], "correctAnswer": 1 },
  { "id": 438, "word": "记住", "pinyin": "jì zhù", "english": "to memorize", "options": ["to forget", "to memorize", "to dance", "to lie"], "correctAnswer": 1 },
  { "id": 439, "word": "简单", "pinyin": "jiǎn dān", "english": "simple", "options": ["hard", "simple", "slow", "deep"], "correctAnswer": 1 },
  { "id": 440, "word": "检查", "pinyin": "jiǎn chá", "english": "to inspect/check", "options": ["to check", "to ignore", "to break", "to sing"], "correctAnswer": 0 },
  { "id": 441, "word": "见面", "pinyin": "jiàn miàn", "english": "to meet", "options": ["to sleep", "to meet", "to return", "to wait"], "correctAnswer": 1 },
  { "id": 442, "word": "健康", "pinyin": "jiàn kāng", "english": "health", "options": ["health", "sorrow", "hunger", "power"], "correctAnswer": 0 },
  { "id": 443, "word": "讲", "pinyin": "jiǎng", "english": "to speak/talk", "options": ["to speak", "to close", "to wait", "to cry"], "correctAnswer": 0 },
  { "id": 444, "word": "教", "pinyin": "jiāo", "english": "to teach", "options": ["to learn", "to teach", "to jump", "to live"], "correctAnswer": 1 },
  { "id": 445, "word": "角", "pinyin": "jiǎo", "english": "corner/angle", "options": ["corner", "street", "room", "sky"], "correctAnswer": 0 },
  { "id": 446, "word": "脚", "pinyin": "jiǎo", "english": "foot", "options": ["arm", "foot", "hair", "face"], "correctAnswer": 1 },
  { "id": 447, "word": "接", "pinyin": "jiē", "english": "to receive/to meet", "options": ["to give", "to receive", "to close", "to call"], "correctAnswer": 1 },
  { "id": 448, "word": "街道", "pinyin": "jiē dào", "english": "street", "options": ["river", "street", "park", "store"], "correctAnswer": 1 },
  { "id": 449, "word": "结婚", "pinyin": "jié hūn", "english": "to marry", "options": ["to divorce", "to marry", "to eat", "to fly"], "correctAnswer": 1 },
  { "id": 450, "word": "结束", "pinyin": "jié shù", "english": "to end/finish", "options": ["to begin", "to finish", "to wait", "to sleep"], "correctAnswer": 1 },

  { "id": 451, "word": "节目", "pinyin": "jié mù", "english": "program/show", "options": ["movie", "program", "lesson", "plan"], "correctAnswer": 1 },
  { "id": 452, "word": "节日", "pinyin": "jié rì", "english": "festival", "options": ["holiday", "festival", "meeting", "day"], "correctAnswer": 1 },
  { "id": 453, "word": "解决", "pinyin": "jiě jué", "english": "to solve", "options": ["to cry", "to solve", "to hide", "to run"], "correctAnswer": 1 },
  { "id": 454, "word": "借", "pinyin": "jiè", "english": "to borrow", "options": ["to lend", "to borrow", "to buy", "to sell"], "correctAnswer": 1 },
  { "id": 455, "word": "经常", "pinyin": "jīng cháng", "english": "often", "options": ["never", "sometimes", "often", "seldom"], "correctAnswer": 2 },
  { "id": 456, "word": "经过", "pinyin": "jīng guò", "english": "to pass through", "options": ["to arrive", "to pass through", "to leave", "to stop"], "correctAnswer": 1 },
  { "id": 457, "word": "经理", "pinyin": "jīng lǐ", "english": "manager", "options": ["worker", "manager", "teacher", "student"], "correctAnswer": 1 },
  { "id": 458, "word": "旧", "pinyin": "jiù", "english": "old", "options": ["new", "old", "slow", "fast"], "correctAnswer": 1 },
  { "id": 459, "word": "久", "pinyin": "jiǔ", "english": "long (time)", "options": ["short", "long", "fast", "slow"], "correctAnswer": 1 },
  { "id": 460, "word": "决定", "pinyin": "jué dìng", "english": "to decide", "options": ["to decide", "to guess", "to wait", "to ask"], "correctAnswer": 0 },
  { "id": 461, "word": "可爱", "pinyin": "kě ài", "english": "cute", "options": ["ugly", "tall", "cute", "lazy"], "correctAnswer": 2 },
  { "id": 462, "word": "渴", "pinyin": "kě", "english": "thirsty", "options": ["hungry", "thirsty", "sleepy", "angry"], "correctAnswer": 1 },
  { "id": 463, "word": "刻", "pinyin": "kè", "english": "quarter (of an hour)", "options": ["minute", "second", "quarter", "hour"], "correctAnswer": 2 },
  { "id": 464, "word": "客人", "pinyin": "kè rén", "english": "guest", "options": ["guest", "host", "teacher", "friend"], "correctAnswer": 0 },
  { "id": 465, "word": "空调", "pinyin": "kōng tiáo", "english": "air conditioner", "options": ["fan", "air conditioner", "heater", "lamp"], "correctAnswer": 1 },
  { "id": 466, "word": "口", "pinyin": "kǒu", "english": "mouth", "options": ["ear", "eye", "mouth", "nose"], "correctAnswer": 2 },
  { "id": 467, "word": "哭", "pinyin": "kū", "english": "to cry", "options": ["to laugh", "to cry", "to sleep", "to write"], "correctAnswer": 1 },
  { "id": 468, "word": "裤子", "pinyin": "kù zi", "english": "pants", "options": ["shirt", "pants", "coat", "hat"], "correctAnswer": 1 },
  { "id": 469, "word": "快", "pinyin": "kuài", "english": "fast", "options": ["slow", "fast", "short", "small"], "correctAnswer": 1 },
  { "id": 470, "word": "快乐", "pinyin": "kuài lè", "english": "happy", "options": ["sad", "angry", "happy", "tired"], "correctAnswer": 2 },
  { "id": 471, "word": "筷子", "pinyin": "kuài zi", "english": "chopsticks", "options": ["knife", "fork", "chopsticks", "spoon"], "correctAnswer": 2 },
  { "id": 472, "word": "蓝", "pinyin": "lán", "english": "blue", "options": ["blue", "yellow", "red", "green"], "correctAnswer": 0 },
  { "id": 473, "word": "老", "pinyin": "lǎo", "english": "old", "options": ["young", "old", "tall", "small"], "correctAnswer": 1 },
  { "id": 474, "word": "离", "pinyin": "lí", "english": "away from", "options": ["close to", "away from", "near", "behind"], "correctAnswer": 1 },
  { "id": 475, "word": "礼物", "pinyin": "lǐ wù", "english": "gift", "options": ["gift", "food", "money", "ticket"], "correctAnswer": 0 },
  { "id": 476, "word": "历史", "pinyin": "lì shǐ", "english": "history", "options": ["math", "history", "language", "geography"], "correctAnswer": 1 },
  { "id": 477, "word": "脸", "pinyin": "liǎn", "english": "face", "options": ["nose", "hand", "face", "mouth"], "correctAnswer": 2 },
  { "id": 478, "word": "练习", "pinyin": "liàn xí", "english": "to practice", "options": ["to sleep", "to practice", "to cry", "to eat"], "correctAnswer": 1 },
  { "id": 479, "word": "凉快", "pinyin": "liáng kuai", "english": "cool (weather)", "options": ["cold", "cool", "hot", "warm"], "correctAnswer": 1 },
  { "id": 480, "word": "两", "pinyin": "liǎng", "english": "two", "options": ["one", "two", "three", "four"], "correctAnswer": 1 },
  { "id": 481, "word": "零", "pinyin": "líng", "english": "zero", "options": ["one", "two", "zero", "five"], "correctAnswer": 2 },
  { "id": 482, "word": "楼", "pinyin": "lóu", "english": "building/floor", "options": ["door", "building", "window", "bridge"], "correctAnswer": 1 },
  { "id": 483, "word": "绿", "pinyin": "lǜ", "english": "green", "options": ["green", "red", "blue", "black"], "correctAnswer": 0 },
  { "id": 484, "word": "马上", "pinyin": "mǎ shàng", "english": "immediately", "options": ["later", "soon", "immediately", "never"], "correctAnswer": 2 },
  { "id": 485, "word": "米饭", "pinyin": "mǐ fàn", "english": "cooked rice", "options": ["noodle", "rice", "meat", "egg"], "correctAnswer": 1 },
  { "id": 486, "word": "面包", "pinyin": "miàn bāo", "english": "bread", "options": ["bread", "rice", "meat", "fish"], "correctAnswer": 0 },
  { "id": 487, "word": "面条", "pinyin": "miàn tiáo", "english": "noodles", "options": ["rice", "bread", "noodles", "water"], "correctAnswer": 2 },
  { "id": 488, "word": "拿", "pinyin": "ná", "english": "to take", "options": ["to give", "to take", "to run", "to wait"], "correctAnswer": 1 },
  { "id": 489, "word": "奶", "pinyin": "nǎi", "english": "milk", "options": ["milk", "water", "juice", "coffee"], "correctAnswer": 0 },
  { "id": 490, "word": "奶奶", "pinyin": "nǎi nai", "english": "grandmother", "options": ["aunt", "mother", "grandmother", "sister"], "correctAnswer": 2 },
  { "id": 491, "word": "南", "pinyin": "nán", "english": "south", "options": ["north", "east", "south", "west"], "correctAnswer": 2 },
  { "id": 492, "word": "难", "pinyin": "nán", "english": "difficult", "options": ["easy", "hard", "fast", "slow"], "correctAnswer": 1 },
  { "id": 493, "word": "你", "pinyin": "nǐ", "english": "you", "options": ["I", "you", "he", "they"], "correctAnswer": 1 },
  { "id": 494, "word": "年", "pinyin": "nián", "english": "year", "options": ["month", "day", "year", "week"], "correctAnswer": 2 },
  { "id": 495, "word": "年轻", "pinyin": "nián qīng", "english": "young", "options": ["old", "young", "short", "weak"], "correctAnswer": 1 },
  { "id": 496, "word": "鸟", "pinyin": "niǎo", "english": "bird", "options": ["fish", "bird", "dog", "cat"], "correctAnswer": 1 },
  { "id": 497, "word": "您", "pinyin": "nín", "english": "you (polite)", "options": ["he", "you (polite)", "we", "they"], "correctAnswer": 1 },
  { "id": 498, "word": "牛奶", "pinyin": "niú nǎi", "english": "milk", "options": ["milk", "juice", "tea", "coffee"], "correctAnswer": 0 },
  { "id": 499, "word": "努力", "pinyin": "nǔ lì", "english": "hardworking", "options": ["lazy", "slow", "hardworking", "tired"], "correctAnswer": 2 },
  { "id": 500, "word": "做", "pinyin": "zuò", "english": "to do", "options": ["to eat", "to drink", "to do", "to sleep"], "correctAnswer": 2 }

]



@words_bp.route('/quiz')
def words_quiz():
    """Render the words quiz page"""
    return render_template('quiz_words.html')

@words_bp.route('/api/quiz-words')
def get_quiz_words():
    """API endpoint to get words for the quiz"""
    try:
        # Get number of questions from request (default 20)
        num_questions = int(request.args.get('count', 20))
        
        # Select random words for the quiz
        quiz_words = random.sample(HSK1_WORDS, min(num_questions, len(HSK1_WORDS)))
        
        # Randomize the position of correct answers
        for word in quiz_words:
            correct_answer = word['options'][word['correctAnswer']]
            random.shuffle(word['options'])
            word['correctAnswer'] = word['options'].index(correct_answer)
        
        return jsonify({
            'success': True,
            'words': quiz_words,
            'total_words': len(HSK1_WORDS),
            'quiz_count': num_questions
        })
        
    except Exception as e:
        return jsonify({
            'success': False,
            'message': f'Error retrieving quiz words: {str(e)}'
        }), 500

@words_bp.route('/api/all-words')
def get_all_words():
    """API endpoint to get all HSK1 words"""
    try:
        return jsonify({
            'success': True,
            'words': HSK1_WORDS
        })
        
    except Exception as e:
        return jsonify({
            'success': False,
            'message': f'Error retrieving words: {str(e)}'
        }), 500

@words_bp.route('/api/next-quiz')
def get_next_quiz():
    """API endpoint to get a new quiz with different words"""
    try:
        # Get previously used word IDs from session
        used_ids = session.get('used_word_ids', [])
        
        # Get available words (not used before)
        available_words = [word for word in HSK1_WORDS if word['id'] not in used_ids]
        
        # If we don't have enough new words, reset and use all words
        num_questions = int(request.args.get('count', 20))
        if len(available_words) < num_questions:
            available_words = HSK1_WORDS.copy()
            used_ids = []
        
        # Select new words
        quiz_words = random.sample(available_words, min(num_questions, len(available_words)))
        
        # Update used word IDs in session
        new_used_ids = used_ids + [word['id'] for word in quiz_words]
        session['used_word_ids'] = new_used_ids
        
        # Randomize the position of correct answers
        for word in quiz_words:
            correct_answer = word['options'][word['correctAnswer']]
            random.shuffle(word['options'])
            word['correctAnswer'] = word['options'].index(correct_answer)
        
        return jsonify({
            'success': True,
            'words': quiz_words,
            'total_words': len(HSK1_WORDS),
            'new_words_count': len(quiz_words)
        })
        
    except Exception as e:
        return jsonify({
            'success': False,
            'message': f'Error retrieving next quiz: {str(e)}'
        }), 500